### ISSUE TITLE
How can I set stage padding ?

### ISSUE THREAD

**Issue by jahid284** [SSENSE/vue-carousel#100]

**Comment by mravinash** [comment]
Add the perPageCustom from  :perPageCustom="[[200, **1**]]" to  :perPageCustom="[[200, **1.1**]]"

**Comment by mravinash** [comment]
@jahid284 Add the perPageCustom from  :perPageCustom="[[200, **1**]]" to  :perPageCustom="[[200, **1.1**]]"

**Comment by guldoe** [comment]
Not like use not integer values, show this error 
 Error in render: "RangeError: Invalid array length"
Could be good has something like 
:stagePadding='50' and do something similar. 

![screen shot 2017-12-12 at 16 04 24](https://user-images.githubusercontent.com/6005590/33893138-06ad7daa-df5b-11e7-91bb-193b2676ab31.png)

Adding a left and right padding.

**Comment by guldoe** [comment]
Adding  this PR https://github.com/SSENSE/vue-carousel/pull/103 to have a solution for statePadding

**Comment by quinnlangille** [comment]
Thanks for the PR @guldoe!
