### ISSUE TITLE
Multiple sliders per page?

### ISSUE THREAD

**Issue by MathsAnderson** [SSENSE/vue-carousel#104]
It would seem that when adding two sliders to a page, the pagination for the first instance doesn't work? Is that a known issue?

**Comment by gangsthub** [comment]
try making a component, so it have its own encapsulation

**Comment by quinnlangille** [comment]
Hey @MathsAnderson, any luck with @gangsthub's suggestion? If not could you provide a JS fiddle with what you're experiencing?

**Comment by midlantica** [comment]
I have the same problem. 

I have two Vue-Carousel components, 
1. A 'Portfolio' images component with arrows left & right.
2. And a 'Quotes' component that shows quotes I like. 

I can get the Portfolio images component working correctly no problem, but the Quotes component is massively wide. It appears to be some weird css flexbox issue. The flex-basis is way too wide: "flex-basis: 2932px". 
`<div class="VueCarousel-inner" style="transform: translateX(0px); transition: transform 0.5s ease; flex-basis: 2932px; visibility: visible;">`

On my Portfolio component, which is good, I have: 
`<slide><img src="x.png"></slide>`

And then:
```
img {
      width: 100% !important;
      height: auto !important;
      background-size: cover !important;
    }
```

So I am at a loss... I'm a bit of a noob but it seems like the JS is not calculating the math correctly?? No idea really. Please help.

*Using latest versions of everything.

**Comment by gangsthub** [comment]
@midlantica that has nothing to do, apparently with this issue. Please, address a new one.

**Comment by quinnlangille** [comment]
Hey @midlantica, you should be able to override the `flex-basis`. The width of the carousel is calculated by `this.$el.clientWitdh`. The flex basis (`slideWidth`) is then determined by the `carouselWidth` / number of pages (`currentPerPage`). Try giving your second carousel a unique id or class and changing it's width in your CSS and you'll hopefully see some results.

Also, @gangsthub is correct in that this should be it's own issue as it doesn't relate to the carousel pagination. No worries, but going forward the best practice is to always open a new issue if you don't see your _exact_ problem. If it ends up as a duplicate I can direct you to the right thread.

**Comment by midlantica** [comment]
I apologize for wrongly putting this here. 😔

**Comment by quinnlangille** [comment]
No worries! I'm going to close this issue now since we haven't heard from OP in a bit. Feel free to open another issue if you're still having problems.
