### ISSUE TITLE
Feature request: auto start

### ISSUE THREAD

**Issue by pushamaku** [SSENSE/vue-carousel#11]
Love this slider so far and it would be even better with an API option to auto cycle through the slides by specifying the interval per slide. An option to loop infinitely or not would be nice as well.

**Comment by toddlawton** [comment]
Thanks a lot for the feedback @pushamaku, both features are definitely coming but unfortunately I don't have a timeframe as of yet.

**Comment by toddlawton** [comment]
Good news! Autoplay is available in [0.4.5](https://github.com/SSENSE/vue-carousel/tree/0.4.3) 🍰

Usage instructions: https://ssense.github.io/vue-carousel/api/#autoplay

**Comment by pushamaku** [comment]
Thanks this is really appreciated! 👍

**Comment by wjl388** [comment]
how to looping  for example  1.img>2.img>3>img>1.img>2.img>3.img  This order

**Comment by percytataje** [comment]
would it be great that when it reaches the end it will restart at the beginning? , or that part is already impeded. help meeeeee
