### ISSUE TITLE
set page programmatically

### ISSUE THREAD

**Issue by jclaessens97** [SSENSE/vue-carousel#112]
First of all really nice component!
Though I'm trying to set the page number programmatically, which it seems there is no straight forward way of doing this? I've tried the following:

`this.$refs.carousel.currentPage = this.selectedTeamId;
this.$refs.carousel.goToPage(this.selectedTeamId);`

In the mounted life-cycle hook of the page where I use the carousel, but no luck. Doing anything wrong? Or have I overlooked something? Thanks in advance & keep up the good work!

PS I noted #77 and #108  but don't seems it's implemented in the npm module?

**Comment by askdesigners** [comment]
And you are sure that you have set the ref attr on the element there? (maybe a dumb question)
I'm doing the same as you and it works pretty well.

**Comment by jclaessens97** [comment]
Yes, I have said the ref attribute to carousel.

**Comment by jclaessens97** [comment]
Problem was somewhere else. the goToPage method doesn't work, but the currentPage does.

**Comment by phaberest** [comment]
I'm trying to achieve the same goal, but as soon as I force it to a certain page, it immediately sets it back to the latest.

**Comment by danielwinther** [comment]
Looking at https://github.com/SSENSE/vue-carousel/pull/108, **ken_mills**'s answer worked for me.
