### ISSUE TITLE
some troubles with initialaizing 

### ISSUE THREAD

**Issue by adFedorovich** [SSENSE/vue-carousel#115]
![screen shot 2018-01-17 at 12 18 42 am](https://user-images.githubusercontent.com/15676325/35012834-3d42e2a6-fb1c-11e7-9cc3-9eea535f7c91.png)

I can not to put carousel to the right side of flexible wrapper

**Comment by quinnlangille** [comment]
Hey @adFedorovich,

Could you elaborate on what you're trying to achieve? A JS Fiddle demonstrating the bug would be really helpful? 

Thanks!
