### ISSUE TITLE
Feature request: Infinite loop

### ISSUE THREAD

**Issue by toddlawton** [SSENSE/vue-carousel#12]

**Comment by incraigulous** [comment]
Hey @toddlawton. Any workarounds for this until you get it implemented?

**Comment by incraigulous** [comment]
OK @toddlawton, I decided to just make a PR. https://github.com/SSENSE/vue-carousel/pull/43

**Comment by HoangAnhEk** [comment]
hello. i'm update a feature infinite loop but isn't work. please help me.
i updated 2 files alike link but my slide isn't loop.
My code slide: 
<carousel :autoplayLoop="true" :autoplay="true" :autoplayTimeout="3000" :autoplayHoverPause="true" :perPage="1" :navigationEnabled="true" :paginationEnabled="false" >

**Comment by rentt1989** [comment]
@HoangAnhEk   use   :loop  instead of :autoplayLoop

**Comment by JonathanMH** [comment]
I would vote for closing this issue to represent that it's actually been

1. developed
2. merged
3. tagged and released on npm

**Comment by prosite5** [comment]
Looks great, but there is one more needed feature - infinite loop without returning back. For example, if I have 3 slides, slider goes 1-2-3 and then moves fast in backwards direction (3-2-1). Would be great, if it goes in the same direction 1-2-3-1-2-3...

**Comment by dawadam** [comment]
Hi,
Documentation need update :

https://ssense.github.io/vue-carousel/api/

**Comment by stephan-v** [comment]
Any update on the infinite loop without reset? Thanks for this awesome component!

**Comment by JonathanMH** [comment]
@stephan-v: it works, you just throw in :loop=true :)

**Comment by stephan-v** [comment]
@JonathanMH The infinite loops works but it simply "jumps" back to the first slide. What I would like(and probably a lot more people) if it is simply kept on going.

So exactly the same animation as if you were to have another slide instead of being at the end of your images.

I have been developing a lot with Vue so I am interested in checking out this project. Perhaps I can help.

**Comment by JonathanMH** [comment]
@stephan-v I get it! Sorry, my mistake!

**Comment by trueChazza** [comment]
hi, is this still in progress? thank you for this library :)

**Comment by lukeheath** [comment]
@stephan-v Yes, I'm also interested in this feature. Perhaps I can help, as well.

**Comment by quinnlangille** [comment]
Hey @stephan-v and others inquiring, this feature was merged in some months ago but the documentation was never updated - the updated docs will be released with the next patch! However, in the mean time all that's required it `:loop=true` on your carousel, as per PR #62

**Comment by lukeheath** [comment]
@quinnlangille Thanks for the heads up. We saw the new feature (which is great), but instead of looping forward naturally the current functionality jumps back through all the slides to get to the end or beginning. We were discussing improving the functionality so that the slides are dynamically re-positioned and can move forward infinitely.

**Comment by khmjcd** [comment]
Is it possible to update the documentation with the "loop" property? :)

**Comment by quinnlangille** [comment]
@khmjcd yeah the doc update with be out with `v0.6.6`

@lukeheath yeah I agree that it would make sense. Maybe it would work as a second value to the `:loop` prop. If anyone wants to implement, feel free to assign yourself to this issue and open a PR!

**Comment by quinnlangille** [comment]
Build is updated with the new docs! Closing this issue. If anyone has any questions or requests concerning loop, feel free to open another issue :octocat:

**Comment by alfligno** [comment]
How to make it not loop back from first slide? or how to make it continuously loop by not moving back to slide 1.

**Comment by Imranki5** [comment]
Add ability to loop around when reaching either end but i want to rotate round,  infinite loop without returning back. For example, if I have 3 slides, slider goes 1-2-3 and then moves fast in backwards direction (3-2-1). Would be great, if it goes in the same direction 1-2-3-1-2-3...
i am facing same issue ? what is the solution ??
