### ISSUE TITLE
Questions: How can I add prefixing for CSS styles?

### ISSUE THREAD

**Issue by martinBadin** [SSENSE/vue-carousel#124]
Please add you prefixes for style, especially for flexbox. Thanks

**Comment by quinnlangille** [comment]
Hi @martinBadin, CSS prefixing is opinionated, and is therefore the users responsibility. See [this](https://github.com/vuejs/vue-loader/blob/master/docs/en/features/postcss.md) for how to configure your Webpack compiler for prefixing. 

Let me know if you have any questions!

**Comment by martinBadin** [comment]
Hi, I using Browserify. Is enything solution for this compiler?

**Comment by quinnlangille** [comment]
Yup, check [here](https://www.npmjs.com/package/browserify-postcss).

**Comment by martinBadin** [comment]
@quinnlangille Thanks. I'll try it
