### ISSUE TITLE
Feature Request: Can you add yarn install instructions?

### ISSUE THREAD

**Issue by roni-estein** [SSENSE/vue-carousel#126]
I've removed npm, and just looking at this lib, for some reason yarn can't find it even though it's on the npm registry

**Comment by quinnlangille** [comment]
Hey @roni-estein, just tried and successfully installed with yarn. What yarn version are you using?

**Comment by roni-estein** [comment]
Nevermind, I re-installed NPM to get this rolling, and it looks like my npm was corrupted, anyhow yarn found the package after npm was uninstalled and re-installed. weird.
