### ISSUE TITLE
Question: How can I only have one slide per page?

### ISSUE THREAD

**Issue by roni-estein** [SSENSE/vue-carousel#127]
Love this super simple carousel! Holy crap setup / read and rolling in 30 minutes! Would be nice to be able to have only 1 review at a time of the design calls for it. However it only goes to 2 as a minimum.

**Comment by quinnlangille** [comment]
Hey @roni-estein, you can achieve this result with `:perPageCustom`, see an example fiddle here -> https://jsfiddle.net/4c05cesu/1/

**Comment by abdulbasithb** [comment]
add `:perPage="1"` on carousel tag 
```
<carousel :perPage="1">
    <slide>
      Slide 1 Content
    </slide>
    <slide>
      Slide 2 Content
    </slide>
    <slide>
      Slide 3 Content
    </slide>
</carousel>
```

**Comment by quinnlangille** [comment]
Going to go ahead and close this since we haven't heard from anyone in a bit. If anyone has any questions/input feel free to open a new issue :octocat:
