### ISSUE TITLE
It is impossible to create endless slider

### ISSUE THREAD

**Issue by NBAH1990** [SSENSE/vue-carousel#135]
Hello!

I want to create endless slider. When I use a :loop directive it always returns me to the first slide, but I want to see the first slide as a next slide.
For example it works in the "slick" carousel, with a parameter "infinite: true".

Could you add it in an API?

Thank you.

**Comment by DanSorahan** [comment]
Dupe of #96

**Comment by NBAH1990** [comment]
@DanSorahan in the #96 issue a topic starter told about ":loop", but "imbolc" told about my topic. I'm not sure that it is a dupe.

**Comment by quinnlangille** [comment]
@NBAH1990 I think @DanSorahan is correct and would consider it a duplicate of the feature request in #96. I'm going to close this in favor, but feel free to make a comment on #96 if you have any questions!
