### ISSUE TITLE
CSS-Styles

### ISSUE THREAD

**Issue by w3code** [SSENSE/vue-carousel#14]
Thanks for the plugin!
Where can we change the CSS-Styles? I tried to set custom styles, but they doesn't work.

**Comment by toddlawton** [comment]
Hi @w3code,

It should be possible to add your own styles to the carousel by using Vue's built in functionality.
One option would be to modify the .carousel, or .slide classes in your parent component. Another option could be to add a custom class to your carousel using:

```
<template>
  <carousel class="my-custom-class" ... >
</template>

<style>
  .my-custom-class {
    ...
  }
</style>
```

Also note there a few styling options that are customizable by props, see the [API Guide](https://ssense.github.io/vue-carousel/api/) for those.

Hopefully this is enough to help, I'll close the ticket and feel free to re-open if you have a feature request.

Cheers!

**Comment by w3code** [comment]
Thanks! I will try it out. 👍

**Comment by AnkitaMagdum** [comment]
How can i override the css properties for this class .VueCarousel-navigation-prev as i want its left: 35px;

**Comment by tsangaris** [comment]
> Hi @w3code,
> 
> It should be possible to add your own styles to the carousel by using Vue's built in functionality.
> One option would be to modify the .carousel, or .slide classes in your parent component. Another option could be to add a custom class to your carousel using:
> 
> ```
> <template>
>   <carousel class="my-custom-class" ... >
> </template>
> 
> <style>
>   .my-custom-class {
>     ...
>   }
> </style>
> ```
> 
> Also note there a few styling options that are customizable by props, see the [API Guide](https://ssense.github.io/vue-carousel/api/) for those.
> 
> Hopefully this is enough to help, I'll close the ticket and feel free to re-open if you have a feature request.
> 
> Cheers!

Hi,

I am trying to customize the appearance of the navigation dots but it does not seem to work. Just to clarify, i am using TailwindCSS and dark mode, where you set 2 different colors to use when switching from light to dark theme. This way the paginationColor and paginationActiveColor will not be of much help in my case.

Also by targeting the VueCarousel-dot and VueCarousel-dot--active nothing happens.

I am using NUXT (Vue) and i write all my CSS in the <style lang="css" scoped"> area in my carousel component.

Somehow the default values are showing.

Thank you for the awesome plugin by the way!

**Comment by 07JP27** [comment]
I have the same issues with @tsangaris. Do you have any updates on this issue?
