### ISSUE TITLE
Bug: pageChange not emitted after drag events

### ISSUE THREAD

**Issue by bepi-roggiuzza** [SSENSE/vue-carousel#145]
Hi, I noticed that pageChange is not emitted after a drag, both with mouse and with touch.
Everything works fine when the current slide changes by a navigation or pagination button.

Tested using
vue 2.5.13
vue-carousel 0.6.9
Firefox, Chrome and Safari at the latest versions

Thanks 👍

**Comment by bepi-roggiuzza** [comment]
Thanks @jdtzmn, really appreciated.
I was very busy at work so I didn't make it by myself, but the idea was the same as yours ;)

**Comment by quinnlangille** [comment]
Hey guys, just wanted to give a heads up that @jdtzmn's fix was released (finally) this morning. Sorry for the delay and thanks for contributing 🎉
