### ISSUE TITLE
Class to slide element ?

### ISSUE THREAD

**Issue by isuke01** [SSENSE/vue-carousel#146]
Hello, 
Is somehow possible to add Class to current visible elements, and class to middle element if there is odd number of visible elements? 

Thanks :) 👍

**Comment by quinnlangille** [comment]
Hey @isuke01, not 100% sure what you mean here can you give an example?

**Comment by stop2stare** [comment]
Hey @quinnlangille , maybe what @isuke01  was trying to say is this:
For example, when VueCarousel has been initiated with `perPage="2"`, *slide 0* and *slide 1* have classes like `VueCarousel-slide VueCarousel-slide-visible`. I think this need is reasonable.
But maybe what @isuke01 really needs is some hook function like `onSlideEnd` to do some customized work.
Later I will push a PR to add this feature.😄

**Comment by quinnlangille** [comment]
I think the implementation should be whatever is the least complicated. I'm not sure if we want to couple it to `perPage`, I'd have to see how the implementation looked. 

However, I _do_ think to expose something in the API for this feature makes the most sense (i.e - pass a prop with a boolean value to enable the feature, or perhaps as we discussed in your PR, pass a prop with a pixel value to customize the look ahead distance).

@stop2stare I actually can't add you as an assignee for some reason, I think it must be the way the SSENSE account is configured, but I'll link your PR on zenhub to show that you're woring on the issue. Thanks for taking the initiative!

**Comment by stop2stare** [comment]
Hello, @quinnlangille . Alright, new PR will be submitted right after [#165](https://github.com/SSENSE/vue-carousel/pull/165) is merged.

**Comment by quinnlangille** [comment]
Hey! Just a heads up that this was resolved with the release of `v0.7.0` -> the visible slides now have an 'active' and 'centre' class. Thanks for making the feature request 👍
