### ISSUE TITLE
Feature request: Dynamic slides with automatic updates

### ISSUE THREAD

**Issue by fabien-lg** [SSENSE/vue-carousel#15]
Hello,

First of all, thanks for this awesome component.
I have a carousel which contains a list of elements. This list is updated so sometimes, the number of items in the carousel changes. 

Is there a way to trigger an update of the carousel ?

For example, now, if I switch from 1 item to 20 items, the pagination doesn't update and all the elements are on the same page.

I tried to call `recomputeCarouselWidth` without success.

Thanks!

**Comment by toddlawton** [comment]
Hi Fabien, thanks a lot for the comment!
This is most likely the next thing I'll be working on. I'll update the ticket as I make progress :)

**Comment by toddlawton** [comment]
Good news! Dynamic slides are available in 0.6.0 🍰
There is an example in the dev sandbox (`npm run dev`)
