### ISSUE TITLE
Bug: pagechange vs. pageChange

### ISSUE THREAD

**Issue by mdix** [SSENSE/vue-carousel#154]
The `pagechange` (or `pageChange`) event is emitted at two locations in the code:

https://github.com/SSENSE/vue-carousel/blob/cdf92d181caae0fa8a422c2c7331844a92522680/src/Carousel.vue#L419
https://github.com/SSENSE/vue-carousel/blob/cdf92d181caae0fa8a422c2c7331844a92522680/src/Carousel.vue#L497

One is written in lowercase (`pagechange`), the other one in lowerCamelCase (`pageChange`). It should be decided on how to write event names in the future and one event name should be renamed according to the new guideline.

**Comment by quinnlangille** [comment]
Hey @mdix, there is an open PR to fix this -> it looks as if there was a bad merge and some duplicate rules got added at some point. The fix will be a part of the v7.0 release hopefully coming by the end of the week

**Comment by quinnlangille** [comment]
Just released the fix for this, let me know if it solves the problem!
