### ISSUE TITLE
BUG: Side Buttons on MS Edge

### ISSUE THREAD

**Issue by jeden1974** [SSENSE/vue-carousel#158]
Don't use Edge myself but just noticed in by browser testing that when using edge you end up with the left/right buttons having a blue button background.

**Comment by quinnlangille** [comment]
Can confirm this, good reporting @jeden1974. I'll flag this as an easy fix, should just be CSS prefixing or something like that.

**Comment by alekpentchev** [comment]
If you don't mind I can take a look at this. Let it be my first open-source contribution. :)

**Comment by alekpentchev** [comment]
I have found what's causing this issue. After the release of Windows 10 some fonts were changed.
Link to the issue here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11844964/

Soon I'll create a pull request for this issue.

**Comment by quinnlangille** [comment]
Just released the fix for this, you can find it in `v0.8.0`! Thanks for reporting and contributing everyone 🎉
