### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by guotie** [SSENSE/vue-carousel#174]
Unable to preventDefault inside passive event listener due to target being treated as passive

**Comment by stop2stare** [comment]
Hey @guotie ,Could you please offer us an example?(哥们儿能给个例子么，或者同时附上中文。。。)

**Comment by guotie** [comment]
```vue
<template>
  <carousel :per-page="1"
    :mouse-drag="true"
    :autoplay="true"
    :autoplayHoverPause="true"
    @change="onBanner">
    <slide v-for="item in slides" v-bind:key="item.id">
      {{item.title}}
    </slide>
  </carousel>
</template>

<script>
import { Carousel, Slide } from 'vue-carousel'
import axios from 'axios'

export default {
  name: 'index',
  data () {
    return {
      slides: [{
        id: 1,
        title: 'Slide 1'
      }, {
        id: 2,
        title: 'Slide 2'
      }]
    }
  },
  components: {
    Carousel,
    Slide
  }
}
</script>


```

**Comment by stop2stare** [comment]
@guotie sorry I can't make this happen again. And we don't use any `{passive: true}` when we add event listener to `touchxxx`.

**Comment by stop2stare** [comment]
Hey @guotie . it's solved, please update vue-carousel to v7.0.1.😄

**Comment by stop2stare** [comment]
@quinnlangille ... It was in the source code in `Carousel`. I didn't check the source carefully... Just take a look at [this line in Carousel](https://github.com/SSENSE/vue-carousel/blob/master/src/Carousel.vue#L552). Maybe I should've deleted this line in the first place... Sorry, My Bad.

**Comment by quinnlangille** [comment]
Just released the fix for this, thanks for the bug report! and double thanks for the fix!

**Comment by matamune94** [comment]
fix please

**Comment by mauriciokruger** [comment]
Hi!, I'm using the version vue-carousel v0.18.0-alpha and the audits sends the following warning: Does not use passive listeners to improve scrolling performance. 

Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. Learn more: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

**Comment by simonmaass** [comment]
i am still having this issue....

**Comment by AlexanderKharchenko** [comment]
I am still having this issue....

Unable to preventDefault inside passive event listener invocation.

`onDrag: function(t) {
                    var e = this.isTouch ? t.touches[0].clientX : t.clientX
                      , n = this.isTouch ? t.touches[0].clientY : t.clientY
                      , i = this.dragStartX - e
                      , r = this.dragStartY - n;
                    if (!(this.isTouch && Math.abs(i) < Math.abs(r))) {
                        t.preventDefault(), <--------
                        t.stopImmediatePropagation(),
                        this.dragOffset = i;
                        var a = this.offset + this.dragOffset;
                        a < 0 ? this.dragOffset = -Math.sqrt(-this.resistanceCoef * this.dragOffset) : a > this.maxOffset && (this.dragOffset = Math.sqrt(this.resistanceCoef * this.dragOffset))
                    }
                },`
