### ISSUE TITLE
Bug: Pagination has extra dot

### ISSUE THREAD

**Issue by quinnlangille** [SSENSE/vue-carousel#178]
Following our recent updates to slide performance, a small bug has occurred where pagination dots are extending one unit past our slide count, see below for an example:

![ezgif com-optimize](https://user-images.githubusercontent.com/17895168/39011032-581b02f6-43de-11e8-9e47-0533db5a2a1b.gif)

This is likely due to some rounding logic somewhere in the new calculations. Should be an easy fix and great for a first time contributor!

**Comment by kulaone** [comment]
@stop2stare, I like your fix, but do we need to remove dots, or maybe color them as selected? 
The dots allow the viewer to know how many slides are out there.

**Comment by stop2stare** [comment]
@kulaone , I agree with your opinion.
> The dots allow the viewer to know how many slides are out there.
But if there are more than one slide per page, say n, and total slideCount is m, then we can only slide `m - n + 1` times in one direction. If so, what does the extra `n - 1` dots supposed to mean? When we click the extra dots, the carousel won't react anyway.
So the problem becomes:
> Do dots means slideCount or times we can slide.

**Comment by kulaone** [comment]
> Do dots means slideCount or times we can slide.
@stop2stare, It's a good question after all the element called pagination, so it needs to be functional as getting the viewer to all possible pages. But as viewers, we got used to seeing it also as a visual "counter" of how many objects/slides are there. 

I think my doubts come from the fact that I'm using vue-Carousel in a slightly different way. I disable the pagination and build an icon menu to navigate between slides. 
In my case, I marked all the visible slide's icons as "Active". 
For example, in a carousel of 6 slides and perPage = 3:
The "menu" start as: 111000
If the viewer clicks on the second icon the carousel will move to the second slide the then menu will be: 011100
But the last 3 icons will point to the 4th slide and the menu will look like 000111 So as you say the carousel won't react but the viewer gets a scene of "where s/he is"

Maybe, best will be to create a new element on vue-Carousel called "Menu" that will bring this functionality to all. I already have the code, just need to make it more global.

**Comment by stop2stare** [comment]
@kulaone alright, I get it. Maybe we need to highlight `perPage` dots at the same time rather than one. In this case, dots will make no misunderstanding and the *menu* functionality has been met also.

**Comment by stop2stare** [comment]
Hi @kulaone , what do you think of this solution?
> highlight `perPage` dots at the same time rather than one.
I mean I do agree that we need some kind of functionality like *menu*, considering multiple slides in one page. But I am still not sure that we should create a new component to meet this need. Maybe we can modify `Pagination` a little bit instead.
Looking forward to your reply.😄

**Comment by kulaone** [comment]
@stop2stare, 
I like the idea of using pagination is a menu. It will also enrich its functionality. Like the adding a value for the pagination location (top, right, left, bottom)

**Comment by quinnlangille** [comment]
I think the right solution involves addressing both of your points. @stop2stare's solution will definitely address the 7 dots on a 6 page slide scenario. However, since this issue is just a bug fix, would it be better to open a feature request for more robust pagination? @kulaone your addition sounds great, though I'd like to see what options would look like without adding a new component as well - I'm not against creating a new one, it as long as it's necessary and the issue can't be solved using our existing components. Excited to see what you guys come up with 🎉

**Comment by quinnlangille** [comment]
If we have 9 slides and `perPage: 3` then there should be 3 dots (3 slides per page, one dot per page) in the pagination. If `scrollPerPage` is `false`, we should have 9 dots, one dot per slide. I made a quick wireframe here: https://wireframe.cc/wpBcFF 

Free free to annotate if you have any questions!

**Comment by stop2stare** [comment]
Well, then we CAN'T **highlight perPage dots at the same time rather than one**...
Hmmm... would you mind clarifying every situation?
1. 6 slides with `perPage: 1`
2. 6 slides with `perPage: 2` and  `scrollPerPage: false`
3. 6 slides with `perPage: 2` and  `scrollPerPage: true`
If this is clarified, the rest would be easy.

**Comment by quinnlangille** [comment]
1. 6 pages, 6 dots
2. 6 pages, 6 dots (if scrollPerPage is false, pagination should ignore `perPage`)
3. 3 pages, 3 dots

**Comment by Stexxe** [comment]
I think this is solution to this issue https://github.com/SSENSE/vue-carousel/pull/221, but I am not sure.

**Comment by syneva-runyan** [comment]
Hi! Not sure if this is an outstanding issue or not, but happy to jump on it if so! My understanding of reading this is that in the scenario with:

+Six Slides
  :per-slide="2"
  :scrollPerPage="false"

EXPECTED BEHAVIOR:  6 Dots are shown in the pagination
ACTUAL BEHAVIOR: 5 Dots are shown in the pagination.

Question: Empty slide spaces. Ex, When the 5th dot is highlighted, the 5th slide is shown at the left side of the carousel, and the 6th slide is shown on the right. When the 6th dot is highlighted, the 6th slide would move over to the left, but there is no 7th slide to show on the right side of the page. What do we show in the 2nd slide space on the last page?

**Comment by quinnlangille** [comment]
Hey @syneva-runyan, thanks for offering to take this one. I think the root cause of this whole issue is a desperate need for refactoring in our slide calculation logic. We're currently working on it in office, but if you'd like to take a crack at improving the logic you're more than welcome!

In regards to your question, I think the best solution is to show an empty place holder slide. i.e - if we have 5 slides and 2 slides per page, the 3rd pagination dot should show the 5th slide and an empty space equal to the width of one slide. Does that seem correct to you?

**Comment by syneva-runyan** [comment]
Seems right to me, I'll take a look!

**Comment by quinnlangille** [comment]
This has been released in 0.18.0 :octocat: Thanks @syneva-runyan for the contribution!
