### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by paulgeisler** [SSENSE/vue-carousel#180]
Is it only me or are the examples really broken?

**Comment by quinnlangille** [comment]
Hey @paulgeisler, definitely not just you! There was a mixup with the CDN version that's causing the bug, going to fix it today. Will ping here once the examples are back online and running. In the mean time, if you have a copy of the carousel locally running `npm run dev` or `yarn dev` will bring up our Vue-Play instance, which has all of the examples running!

**Comment by paulgeisler** [comment]
Thanks!
