### ISSUE TITLE
Bug: "Can't read currentPage of undefined" on jsFiddle

### ISSUE THREAD

**Issue by quinnlangille** [SSENSE/vue-carousel#182]
Locally there is no issue regarding currentPage, it console logs at every point in the application and is visible in vue-dev-tools. However, on JSfiddle all of our examples are broken - this includes our embedded slider on the main https://ssense.github.io/vue-carousel/ page. 

The error we're receiving in the console is:

![screen shot 2018-04-20 at 11 51 47 am](https://user-images.githubusercontent.com/17895168/39061421-28a7c3ce-4492-11e8-8b9d-283a69b6e889.png)

**Comment by quinnlangille** [comment]
@stop2stare it seems as if the `Slide` can't see `this.carousel` with the new `provider/injection` format - does something need to be updated in the JSfiddle to accommodate this change? 

Both provided and injected components are coming through in the console so nothing wrong there

**Comment by quinnlangille** [comment]
Looks like this was just due to jsFiddle using an old version of vue 😅

**Comment by stop2stare** [comment]
@quinnlangille haha, `provide/inject` was added in `v2.2.0+`. But maybe we should've added a statement in README that `vue-carousel` requires `Vue v2.2.0+`.
