### ISSUE TITLE
Feature: Autoplay timeout should reset when manually switching slides

### ISSUE THREAD

**Issue by paulblyth** [SSENSE/vue-carousel#184]
Hi! Using v0.7.2 and I've set `v-bind:autoplayTimeout="5000"` which works perfectly until you manually move forwards or backwards in the carousel, at which point the timeout doesn't appear to be resetting and the current slide will slide in a fraction of the time.

e.g. I have slides A, B, C and D with a 5 second autoplay. When it auto-slides to B, I wait for 2.5 seconds and manually move to C. I'd expect a 5 second delay before it slides to D but it only waits the remaining 2.5 seconds.

I don't think I'm missing anything.. but I'll keep digging

**Comment by stop2stare** [comment]
Hey @paulblyth , thanks for the issue, could you please leave a piece of your code?

**Comment by quinnlangille** [comment]
Hey @paulblyth, I think this is actually a feature request as the carousel currently does not reset the timeout on manual page transition. I'll flag this as a feature and hopefully we'll have a contributor take the task on!

P.S - the TypeError was just resolved with the most recent release! 🎉

**Comment by yorrran** [comment]
Hey, will add goToPage(page) {
      ...
        this.autoplayInterval = 5000;
      }
    }, work for this issue? How can i test if it works fine locally after modification?

**Comment by ERPedersen** [comment]
I can have a fix for this ready for this soon

**Comment by quinnlangille** [comment]
@ERPedersen that would be great! Looking forward to the PR :~)

**Comment by Calinou** [comment]
Should this issue be closed, now that https://github.com/SSENSE/vue-carousel/pull/216 has been merged?

**Comment by quinnlangille** [comment]
Hey @Calinou, good call! Forgot to wrap this one up. Will close now, thanks for notifying :octocat:
