### ISSUE TITLE
Bug: IE11 is not working - needs investigation

### ISSUE THREAD

**Issue by yu-sungho** [SSENSE/vue-carousel#201]
I don't know why ie11 is not working

**Comment by quinnlangille** [comment]
Hey @yu-sungho, ie11 usually requires some extra effort with ES6 and front end frameworks. It seems we lost support for IE when we rolled up to `Vue@2.5`, so we likely will need to polyfill an unsupported tag or feature. I'll switch this to a bug report and see if anyone can help us out :~) 

Thanks for reporting, if you fix it in the mean time feel free to open a pull request 💻

**Comment by Nijhazer** [comment]
I've recently run into this issue on an app that uses Nuxt. As a workaround, we're running autoplay.js through babel-loader.

**Comment by quinnlangille** [comment]
Just a heads up, there was already a ticket open for this issue so lets continue any discussion on #190
