### ISSUE TITLE
Question: How can I set an index slide?

### ISSUE THREAD

**Issue by VCodepp** [SSENSE/vue-carousel#203]
How can I adjust the slide index when the slider is created? I also called the discovery, but I could not find it.

I want to start from the second slide when I switch from one page to a slide.

I use vue-cli

**Comment by quinnlangille** [comment]
Hey @VCodepp, you can pass the `navigateTo` prop as `:navigateTo=1` to move to the second slide. It's not in the documentation yet, but you can find it in the prop listings in the `src/Carousel.vue`

Lemme know if that works!

**Comment by donaldr** [comment]
It doesn't work for me

`
<carousel :perPage=1 ref="rCarousel" class="quotes" v-on:pageChange="pageChanged" paginationActiveColor="#b50101" :minSwipeDistance=12 paginationColor="#444444" :paginationPadding=20 :paginationSize=20 :navigateTo=2>
`

Carousel stays at index 0.

**Comment by quinnlangille** [comment]
Hmm just tested it and you're correct! Seems like there is a bug in the prop. I'll open a ticket to resolve it :~)

**Comment by quinnlangille** [comment]
I've opened a ticket for it's resolution here #220. Feel free to continue the conversation there, will close this in the mean time :~)

**Comment by donaldr** [comment]
Thanks!

**Comment by bartdominiak** [comment]
You can just add this:
```
      mounted() {
        this.$refs['carousel'].goToPage(this.$refs['carousel'].getNextPage());
      }
