### ISSUE TITLE
Invalid animation direction when 2 images and swipe

### ISSUE THREAD

**Issue by Exalax** [SSENSE/vue-carousel#210]
Two things must happen:
1. Two slides
2. Swiping

Clicking to arrays is ok and produce right result
Browser independent

**Comment by Exalax** [comment]
Confirmed to 0.8.0

**Comment by quinnlangille** [comment]
Hmmm, this must have something to do with carousel width calculation. Any chance you can provide a jsfiddle or link to an example of this?

**Comment by Exalax** [comment]
Sorry, my bad. No problem with library code.
