### ISSUE TITLE
How to replace navigation button css selector?

### ISSUE THREAD

**Issue by omduel** [SSENSE/vue-carousel#213]
I would like to change the navigation button icon to picture instead. 
I cannot replace it with such as ".VueCarousel-navigation-button" or "button.VueCarousel-navigation-button.VueCarousel-navigation-next.VueCarousel-navigation--disabled".
What did I mistake?

Thank you for your good component.

**Comment by quinnlangille** [comment]
Hey @omduel - there's no native way to do this yet, but you'll find a few workarounds in #88 

Going to close this in favour of that, if you have in questions feel free to continue the conversation there :~)
