### ISSUE TITLE
Bug: Empty slides at the end of carousel

### ISSUE THREAD

**Issue by PawelDmochowskiDRAST** [SSENSE/vue-carousel#215]
When carousel is set to per-item scrolling manual navigation on last page and autoplaying has to scroll through every visible item even when it does not affect the position of the carousel.

For example:
- carousel has 10 slides
- **perPage** is set to **6**
- **scrollPerPage** is set to **false**
- **loop** is set to **true**
- **navigationEnabled** is set to **true**
- navigating "next" scrolls the carousel 4 times it is used
- subsequent 5 "next" navigations do not scroll the carousel
- 10th "next" navigation loops the carousel back to starting position

From users perspective I would assume that it should go to the beginning right after it has reached the last possible scrolling position.

**Comment by quinnlangille** [comment]
Hey @PawelDmochowskiDRAST, this should be addressed with the latest release `v0.9.0`. Lemme know if it fixes it!

**Comment by PawelDmochowskiDRAST** [comment]
Actually the result is... worse (using the same setup as described).
Now after navigating 4 items right subsequent 3 item insert empty slides from the right side before finally looping back to start.

Expected behavior would be:
- N - number of slides
- P - current page length
After navigating to slide N-P (0-based) subsequent navigation to next should loop.

**Comment by quinnlangille** [comment]
Hmmm, can you link me to an example of what you're seeing? Just so we're on the same page. I'll issue a bug fix request once I have an example to post!

**Comment by PawelDmochowskiDRAST** [comment]
Sure.

https://codepen.io/PawelDmochowski/project/editor/AyMxVN

**Comment by wk93** [comment]
I have same problem on SSR.

**Comment by quinnlangille** [comment]
Switched this to a bug report, thanks for the repro!

**Comment by toddgroff** [comment]
I just submitted a PR #246 to fix this issue.

**Comment by quinnlangille** [comment]
Releasing the fix shortly, just merged and testing now. As an aside to this, I'll likely add to the roadmap to beef up our testing in this area, so we don't have this kind of thing happen again. If anyone's interested in helping with the tests (because you like writing them, or want to learn more about them), feel free to write here, here -> #143,  or email me at quinn.langille@ssense.com!

**Comment by quinnlangille** [comment]
Released with v0.10.0 - https://github.com/SSENSE/vue-carousel/releases/tag/v0.10.0

Thanks so much to everyone for reporting and especially to @toddgroff for the fix! If there are any outstanding issues that were resolved with this fix, feel free to open a new issue :~) 

Going to close this one now, great work everyone 🎉
