### ISSUE TITLE
Dynamic Slide with two columns don't work very well 

### ISSUE THREAD

**Issue by agtoncerqueira** [SSENSE/vue-carousel#219]
I've trying to do a dynamic slide with two columns separate each one, but the main div size render small, when I click on slide or resize the window the div become with your normal size.
Use inspector to analyze, i realize that class .VueCarousel-inner begin with this value "flex-basis: 810px"  and after resize widow it change to "flex-basis: 1140px".
Here is my code:
```
<carousel v-if="projects.length"
            :perPage="1"
            paginationActiveColor="#4d2df5"
            paginationColor="#b2ebd1"
            :scrollPerPage="false"
            >
              <template v-for="(project, index) in projects">
                <slide>
                  <div class="col-md-4">
                    <h3 class="title_project">
                       <router-link :to="{ name: 'details', params: { slug: project.slug }}" >   {{ project.title.rendered }}</router-link>
                    </h3>
                    <span class="badge badge-primary" v-for="tags in project.tags_jobs_name ">{{ tags.name }} </span>
                  </div>

                  <div class="col-md-8">
                    <img :src="project.better_featured_image.media_details.sizes.large.source_url" class="tilter__image">
                  </div>
               </slide>
               </template>
  
          </carousel>
```

I think that problem happen because :perPage="1" not identify suddenly. 
Since now, Thanks for help me!!!

**Comment by quinnlangille** [comment]
Hey @agtoncerqueira, are rendering these carousels on the server or the client? I've seen a similar issue with SSR but never with regular rendering

**Comment by agtoncerqueira** [comment]
Hey @quinnlangille I'm rendering from the server, but i don't know what happened everything is working well again...
The Config is the same, I just added ":paginationSize="12"" but this it's not too important. My project back normal without explanation I hope that keep like this in the future on production!

Sorry me for take a long time to answer!!!

**Comment by quinnlangille** [comment]
Hey @agtoncerqueira, we've been doing quite a bit of development in the past few weeks, so it's likely this issue was resolves as a side-effect from one of the releases. I'll close the issue, thanks for responding!
