### ISSUE TITLE
Bug: NavigateTo prop is not working as expected

### ISSUE THREAD

**Issue by quinnlangille** [SSENSE/vue-carousel#220]
When defining a carousel with a default `:NavigateTo={index}` prop, the carousel should start on the given index.

**Comment by quinnlangille** [comment]
This has been resolved by #222!

**Comment by isferrei** [comment]
@quinnlangille Was this issue resolved? because you're redirecting to #222 and #222  is redirecting to #221 and I can't see any fixing for bug with navigateTo
