### ISSUE TITLE
Question: How do I dynamically change autoplay? The prop does not stop it

### ISSUE THREAD

**Issue by bakuryuthem0** [SSENSE/vue-carousel#229]
I have this carousel

`    <carousel :loop="true" :per-page="1" :autoplay="doAutoplay" :autoplay-timeout="4000" :pagination-enabled="false" :mouse-drag="false">`
   ` ...Here are a bunch of slides`
    `</carousel>`
i have a button that toggle the `doAutoplay` for the `autoplay` prop, in the beginning it contains true. the problem is, when the `doAutoplay` is toggle, the autoplay does not stop, but i can see the prop's value in the component have changed.

I am using `"vue-carousel": "^0.8.1"`.

**Comment by quinnlangille** [comment]
Hey @bakuryuthem0, mind trying this with 0.9.0? We just release it, and it has a reset feature on hover that might make this work. Otherwise, it looks like it'll require a custom watcher
