### ISSUE TITLE
Loop option missing from API Documentation

### ISSUE THREAD

**Issue by cicsolutions** [SSENSE/vue-carousel#230]
Hi, I just wanted to note that the github instructions DO mention the loop option, however the API docs DO NOT mention the loop option.
https://ssense.github.io/vue-carousel/api/

Thanks for such a great component, and all that you do!

**Comment by quinnlangille** [comment]
Yeah that has been in the plan to add that to official docs for weeks now and it keeps getting pushed back, thanks for reminding me!

**Comment by quinnlangille** [comment]
I've created #262 to cover the doc updates, going to close this in favor of that. Feel free to make any comments/suggestions there!
