### ISSUE TITLE
Empty slides on the last page

### ISSUE THREAD

**Issue by dvasyliev** [SSENSE/vue-carousel#237]
When I have 10 slides which should show per 3 on the each page, I see only one slide on the last page. In the version 0.7.1 all works fine!

Fox example its my slider with slides on the each page:
page 1: [0, 1, 2]
page 2: [3, 4, 5]
page 3: [6, 7, 8]
page 4: [9, _, _]

Is should be like this on the 4th page:
page 4: [7, 8, 9]

When I haven't enough slides for last page, I should see few slides from previous page.

**Comment by dvasyliev** [comment]
[Here](https://jsfiddle.net/k18Laxhv/) is example 
P.S. Go to the last page

**Comment by dvasyliev** [comment]
It's [example](https://jsfiddle.net/nxym5gjz/) from version 0.7.1 where on the last page I can see correct slides. But, there are some strange behavior, on the last page I see [7, 8, 9] slides, but when I go to the previous page I see [6, 7, 8] slides, will be better show [4, 5, 6] slides. 
Logic in that, when you will able show 3 next/previous slides - you show! When there are less then 3 slides on the next/previous page you should show those slides + one or more slides from current page.

**Comment by quinnlangille** [comment]
Hey @dvasyliev, thanks for detailed reporting! This is actually a bug that was introduced with the last update. There is an open issue for its resolution that you can follow here -> #215

Going to close this in favor of that, but feel free to move your comments over there :~)

**Comment by dvasyliev** [comment]
@quinnlangille sure!
Hope you will fix it as soon as possible :)

**Comment by quinnlangille** [comment]
Yeah there are a few people who have already mentioned they're working on solutions, so we'll hopefully see some contributions for it over the weekend
