### ISSUE TITLE
Bug: Carousel Does not Reset To show all slides when windows is resized.

### ISSUE THREAD

**Issue by hang15** [SSENSE/vue-carousel#241]
I created a carousel with the following properties
```
:navigationEnabled="true" 
:paginationEnabled="false"
:perPageCustom="[[170, 1], [350, 2], [510, 3], [660, 4]]"
```
and 4 square slides of fixed size 130px.

First I resized the window to show only one slide and navigate to the last slide.
Then I maximized the window.
The carousel is stuck at showing only the last slide and unable to advance backwards with the pagination keys.

**Comment by quinnlangille** [comment]
Hey @hang15, this seems to be working fine for me. Can you send a jsFiddle or a link to an example of it happening so we can take a look? Thanks!

**Comment by quinnlangille** [comment]
Ah cool! Will close this then, thanks for the update :octocat:
