### ISSUE TITLE
Navigation arrow does not fade on last slide

### ISSUE THREAD

**Issue by adambartosiewicz** [SSENSE/vue-carousel#242]
It looks like the right arrow of pagination does not fade anymore when on the last slide. The occurs in the latest (0.9.0) version. When switched  to 0.8.1 it works as expected.

**Comment by quinnlangille** [comment]
Hey @adambartosiewicz, this is related to #215. A bug with slide count calculation was introduced with an update. Going to close this you can follow the progress and post any findings there! Thanks
