### ISSUE TITLE
Bug: IE11 specific: Carousel examples are missing

### ISSUE THREAD

**Issue by hitozz** [SSENSE/vue-carousel#247]
https://ssense.github.io/vue-carousel/examples/

Reproduced on Win10, IE11

See screenshot: https://i.imgur.com/dWU264W.png

**Comment by quinnlangille** [comment]
Hey @hitozz, our examples are just embeds of JSfiddles, so unfortunately I think it's an issue on their end. I'll check our github page branch and see if I can play with the babel config, but I doubt the issue is in transpilation

**Comment by hitozz** [comment]
Thanks @quinnlangille !

**Comment by quinnlangille** [comment]
Just released a polyfill that should cover some IE compatibilities, I don't have any wayt o test on IE so if you get a minute would you mind taking a look to see if that fixed it @hitozz - otherwise, it's an issue on JSFiddles end

**Comment by hitozz** [comment]
Checked on IE11. 
Still not fixed. Looks like this should be addressed to JSFiddles.

https://i.imgur.com/0407Kmg.png

Thanks for your effort anyway! @quinnlangille
