### ISSUE TITLE
BUG The carousel shifts to the right if slides have at least 1px border.

### ISSUE THREAD

**Issue by hitozz** [SSENSE/vue-carousel#250]
Steps:
1. Go to Examples page: https://ssense.github.io/vue-carousel/examples/
2. Navigate to the last slide
3. Add border: 1px solid #000; to the .VueCarousel-slide {

Actual result: carousel has shifted to the right.

See screenshots:
https://i.imgur.com/tAsJCv4.png
https://imgur.com/a/hIplEys

**Comment by quinnlangille** [comment]
I think this is to do with adding border through the inspector. As the carousel width is calculated on render, changing the border will add 2px to each slide, without recalculating the width of the carousel.

If you add the border in your CSS and properly re-render, it will likely work out fine!
