### ISSUE TITLE
Both yarn.lock and package-lock.json

### ISSUE THREAD

**Issue by RyanLiu0235** [SSENSE/vue-carousel#258]
Hi guys, I haven't checked this project for a long time, and I notice that there are both yarn and npm lock file now. Maybe this is caused by different contributors' MR. Anyway, I don't think this is good, at least it's not concise(?).
How about use only yarn instead?

**Comment by quinnlangille** [comment]
Hey @RyanLiu0235, good to hear from you again! Yeah good catch, the `package-lock.json` must have made it into the last release. I'll review you PR right now and get it merged in!

**Comment by quinnlangille** [comment]
This was resolved by another PR! Going to close this, but if you have any questions/comments feel free to reopen or make a new issue :octocat:
