### ISSUE TITLE
0.10.0 three times larger then 0.9.0 in result bundle

### ISSUE THREAD

**Issue by DreaMinder** [SSENSE/vue-carousel#260]
Using nuxt analysis tool, it shows that .9 version is 27kb parsed, 8kb gziped and .10 is 114kb parsed, 36 gziped.
It would be better to make it as lightweight as possible. For me low size is the main advantage of this component.

**Comment by quinnlangille** [comment]
Hey @DreaMinder, I've received a few e-mails regarding the size increase and am currently investigating. I think it's likely attributed to some work on our babel/webpack config - will update here once a solution has been merged in!

**Comment by quinnlangille** [comment]
This has been resolved with the release of `v0.12.0`, bundle size should be down to ~25kb. Going to close this now, feel free to open a new issue or comment here again if there are any other bundle size issues! Thanks for reporting :octocat:
