### ISSUE TITLE
Interval on each slide

### ISSUE THREAD

**Issue by jorgeuos** [SSENSE/vue-carousel#265]
Is there a way to change how long a slide is visible?
I've tried to change `:speed=800` but it only changes the speed of the transition.

**Comment by quinnlangille** [comment]
Hey @jorgeuos, could you elaborate on this? Do you mean you want to delay between transitions?

**Comment by jorgeuos** [comment]
The time one slide stays in focus. Idk how long it is now, but our designer wanted one second extra for our slides.

**Comment by quinnlangille** [comment]
There's an open feature request for a delay right now, which sounds like what you're looking for => #196 

Someone's mentioned that they'd create the feature but I've seen no PR from them yet. Any updates regarding it will happen in that thread. If you end up engineering something in house, feel free to submit a PR!

**Comment by jorgeuos** [comment]
Yes! Looks like it, pretty much. I'll see if I have time over to do it! I'll close this then!
