### ISSUE TITLE
Feature Request: add href option to slide to make it act like an anchor

### ISSUE THREAD

**Issue by SAL-MichaelZanggl** [SSENSE/vue-carousel#267]
I think it is a very common way to use links for slides, unfortunately using an anchor tag inside `Slide` has a caveat.

I currently implemented the slide like this
```
<Carousel>
	<Slide 
		v-for="item in items"
		v-bind:key="item.id"
	>
		<a :href="item.url">
			<img :src="item.image">
			<h5 class="ellipsis">{{ item.title }}</h5>
		</a>
	</Slide>
</Carousel>
```

When I start dragging while on a slide and release while the mouse is still on the same slide the browser navigates to the respective `item.url`.

Doing this using `slideClick` is not possible since the function also gets triggered with a middle or right click, among other caveats.

Proposed solution:
```
<Carousel>
	<Slide 
		v-for="item in items"
		:key="item.id"
                :href="item.url"
	>
		<img :src="item.image">
		<h5 class="ellipsis">{{ item.title }}</h5>
	</Slide>
</Carousel>
```

**Comment by quinnlangille** [comment]
Hey @SAL-MichaelZanggl, I missed this issue sorry for the delay! This is possible, but will also be resolved by #172 which is in our v1 roadmap. Going to close this, but if you have any concerns feel free to make a comment on #172 :octocat:
