### ISSUE TITLE
Feature request: navigation handle within Carousel

### ISSUE THREAD

**Issue by wenxin3262** [SSENSE/vue-carousel#27]
Can we add a prop that make the navigation handles locate inside the carousel div? 

It might be just add a prop that changes `.VueCarousel-navigation-*` class `left` or `right` value.

Thanks

**Comment by toddlawton** [comment]
Hi @wenxin3262, would you like to contribute a PR for this?

**Comment by toddlawton** [comment]
Please see the resolution comment here: https://github.com/SSENSE/vue-carousel/issues/34#issuecomment-286531151

Cheers!
