### ISSUE TITLE
Get the displayed page and execute function

### ISSUE THREAD

**Issue by SueIte** [SSENSE/vue-carousel#271]
Hi there!
I do have a simple question - how can I achieve the following:
I want to change images outside the slider when the a particular content/slide is displayes within the slider. So I need a way to get an event like "slide 1 in View", "slide 2 on View" and so on, so that I can execute a function. Whats important - I need it to work when the specific slide is visible or slided into view, because the content of the slide describes the image which is the background of my site.

Does anyone know how to achieve that?

Thanks in advance

**Comment by Cre3z** [comment]
@SueIte have you found a solution to this yet?

**Comment by quinnlangille** [comment]
Hey @SueIte, @Cre3z. We append a class on all active slides (`VueCarousel-slide-active`) when they come into view. You could likely make something work based on slides that gain/lose that class. 

As for finding the index, we don't currently emit any events that expose that info. We have hooks to dynamically change index from the outside, but not the other way around. 

However, depending on your content, you could likely engineer something based on the CSS class.

Alternatively, adding a feature to emit the current slides in view wouldn't be difficult. If you wanted to make a contribution to the repo, feel free!

**Comment by quinnlangille** [comment]
Since I haven't heard back I'll assume the classes fixed the issue! Going to close this, but feel free to reopen or make a new issue if anything else comes up :octocat:
