### ISSUE TITLE
Carousel doesn't take slide padding, border size into consideration when calculating width

### ISSUE THREAD

**Issue by paperscissors** [SSENSE/vue-carousel#277]
So it looks like if your carousel is set to only show one slide, and you've got padding or borders setup, it doesn't factor those into the width calculations of each slide in the carousel.

So, say for example I have slides that are the width of the carousel, but also have `padding: 85px` set on them, the first slide is 85px wider than the carousel, the second is offset from the left edge of the carousel by 85px, the third by 170px, so on in a cascading manner.

Probably not a bad idea to be checking padding, border, etc in addition to slide widths when initializing. Thanks!

**Comment by quinnlangille** [comment]
Forgot to close this with my last comment, going to now!
