### ISSUE TITLE
No way to tell if carousel has loaded

### ISSUE THREAD

**Issue by jorgvm** [SSENSE/vue-carousel#280]
Hey,

When the carousel is loaded, I want to navigate to a certain page number. I can change the "navigateTo", but only when the carousel is loaded. And I don't know when the carousel is actually loaded (I'm using SSR)

With an emit, a parent component can know if the Carousel is done loading:
https://github.com/SSENSE/vue-carousel/pull/279

Or am I missing something and can this already be done some other way?

(Also, if I have a suggestion, would you prefer an issue like this, or is a PR enough?)

Thanks,
Jorg

**Comment by quinnlangille** [comment]
Hey @jorgvm, yeah that sounds like a good addition. I think you can do this in Vue itself, but it's not super nice looking and this is pretty low impact for a way cleaner solution. 

For small features like this, just a PR is usually fine!

**Comment by jorgvm** [comment]
thanks!

**Comment by quinnlangille** [comment]
No worries! Just released your fix, will close this now. Thanks a million for the contribution! Hope to see some PRs from you again :~) :octocat:
