### ISSUE TITLE
carousel not working for slides. I have linked bootstrap.min.js, bootstrap.min.css & bootstrap-theme.min.css

### ISSUE THREAD

**Issue by sukumarghy** [SSENSE/vue-carousel#285]
<div class="container">
<div class="row">
  <div class="col-sm-12">
    <div id="slider" class="carousel slide" data-ride="carousel">

      <div class="carousel-inner" role="listbox">

        <div class="item active">
          <img src="D:\PYTHON PROJECTS\IMAGES\wallpaper2you_362137.jpg" alt="download" />
            <div class="carousel-caption">
              <h1>SERVER</h1>

            </div>
        </div>

        <div class="item active">
          <img src="D:\PYTHON PROJECTS\IMAGES\wallpaper2you_362138.jpg" alt="download" />
            <div class="carousel-caption">
              <h1>HIGH</h1>

</div>
        </div>

      </div>

    </div>

  </div>

</div>
</div>

**Comment by rodrigofazenda** [comment]
Hi @sukumarghy, you are in the wrong project. You are talking about a Bootstrap Carousel, this is a Vue.js Carousel.

**Comment by quinnlangille** [comment]
Yeah @rodrigofazenda is right! Going to close this
