### ISSUE TITLE
API Documentation not updated

### ISSUE THREAD

**Issue by nuke99** [SSENSE/vue-carousel#286]
I see functionalities such as `advancePage()` in source code. but they are not mentioned in the Public API documentation.  is there a specific reason for this? I would like to use the function `advancePage` but since it's not mentioned in the documentation not sure if I should 😕. 

Please give an update 😁

**Comment by quinnlangille** [comment]
Hey @nuke99, documentation update is on the roadmap for v1. Should happen in the next few weeks!

**Comment by quinnlangille** [comment]
Forgot to mention that we have #262 that covers the documentation epic for the roadmap. I"m going to close this in favor of that, so feel free to make any comments/suggestions there! :octocat:
