### ISSUE TITLE
scrollPerPage doesn't work 0.14.0 in nuxtjs

### ISSUE THREAD

**Issue by matamune94** [SSENSE/vue-carousel#295]
when i change :scrollPerPage="false"  and make error : RangeError: Invalid array length
can help ?

my code :

> <template>
  <div class="mycarousal">
  <no-ssr>
    <carousel :scroll-per-page=false>
      <slide>
        <span class="label">Slide 1 Content</span>
      </slide>
      <slide>
        <span class="label">Slide 2 Content</span>
      </slide>
      <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
      <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
      <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
      <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
     <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
     <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
     <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
     <slide>
        <span class="label">Slide 3 Content</span>
      </slide>
    </carousel>
  </no-ssr>
  </div>
</template>

<style>
  .mycarousal{
    left: 50%; 
    top: 50%;
    position: relative;
    width: 700px;
    transform: translateX(-50%);
  }
  .VueCarousel{
    display:inline-block;
  }
  .VueCarousel-slide {
    position: relative;
    background: #42b983;
    color: #fff;
    font-family: Arial;
    font-size: 24px;
    text-align: center;
    min-height: 100px;
  }
</style>

**Comment by matamune94** [comment]
no works as expected , scrollPerPage and per-page is different , ex : you have a page with 4 item and you want scroll on 1 item when Dragmouse if no have scrollPerPage , you will scroll 4 item next not 1 item , i need fix it

**Comment by matamune94** [comment]
need help please!!!

**Comment by Defite** [comment]
@matamune94 well, forget to mention that I'm already using this option, sorry.

**Comment by quinnlangille** [comment]
Good to see you fixed @matamune94, will close this!
