### ISSUE TITLE
[customize dots] Is it able to move dot pagination over the slides? 

### ISSUE THREAD

**Issue by juneyoung** [SSENSE/vue-carousel#298]
Is it possible to customize dot styles? I want to move those dots over the slides. (I think you could understand what I mean. The basic sample of the official site is dot located under the slides.)
In my component, I declare vue-carousel like 

```
  	<carousel
		:scrollPerPage="true" :mouseDrag="false"
		:perPage="1">
		<slide v-for="(item, index) in slides" :key="index">
			<nuxt-link :to="$getHref(item.linkTo)">
				<img :src="item.imageUrl" @error="setDefaultImageUrl" alt=""/>
			</nuxt-link>
		</slide>
	</carousel>

... 

<style scoped>
       .VueCarousel-wrapper {
		position: absolute !important;
		z-index: -10 !important;
	}

	.VueCarousel-pagination {

	}
</style>
```
But it ignores the style in the component. 

I think this UI feature is very common so there might be pre-implemented form in vue-carousel but could not find its official website.

Thanks.

**Comment by quinnlangille** [comment]
Hey @juneyoung, there have been a few issues regarding this before and I _think_ this can resolved with the new slots we deployed fir navigation and pagination in `v0.15.0` - [here's the commit for that](https://github.com/SSENSE/vue-carousel/commit/e9e57149a65f800b5d918723dc17e25856290cb9).

We don't have the feature documented yet, it will be coming as part of #262. 

Lemme know if that will help! If you end up implementing, feel free to send over a snippet and I can use it as an example in out documentation
