### ISSUE TITLE
Unable to use vue-carousel as a local package

### ISSUE THREAD

**Issue by rkomiyama** [SSENSE/vue-carousel#302]
## Bug Report

**Current Behavior**
Unable to use vue-carousel as a local package using `yarn link`. The following warnings are produced:

```
➜  ryu-carousel-cli git:(master) ✗ yarn serve
yarn run v1.10.1
$ vue-cli-service serve
 INFO  Starting development server...
 98% after emitting CopyPlugin

 WARNING  Compiled with 2 warnings                                                                                                                     12:29:37 AM

 warning  in ./src/App.vue?vue&type=script&lang=js&

"export 'Carousel' was not found in 'vue-carousel'

 warning  in ./src/App.vue?vue&type=script&lang=js&

"export 'Slide' was not found in 'vue-carousel'
```

**Input Code and steps to reproduce**
`App.js`
```js
<template>
  <div id="app">
		<carousel :per-page="1" :custom-slide-width="1">
			<slide>
				Slide 1 Content
			</slide>
			<slide>
				Slide 2 Content
			</slide>
		</carousel>
	</div>
</template>

<script>
import { Carousel, Slide } from 'vue-carousel'

export default {
	name: 'App',
	components: {
		Carousel,
		Slide
	}
}
</script>
```

**Expected behavior/code**
Doing a `yarn link` should allow me to use `vue-carousel` in a local project.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "name": "ryu-carousel-cli",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "vue": "^2.5.17",
    "vue-carousel": "file:../vue-carousel"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.5",
    "@vue/cli-plugin-eslint": "^3.0.5",
    "@vue/cli-service": "^3.0.5",
    "vue-template-compiler": "^2.5.17"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

**Environment**
- "@vue/cli-plugin-babel": "^3.0.5"
- Node/npm version: Node 11.0.0/npm 6.4.1
- OS: macOS 10.12.6

**Comment by quinnlangille** [comment]
Hey @rkomiyama, yarn has an [open issue](https://github.com/yarnpkg/yarn/issues/2914) that's likely effecting this. I can recreate this issue on local if I use `yarn link`, but it works fine if instead I point to my local directory with node_modules installed in my package json (i.e `vue-carousel: link: ../path/to/vue-carousel`)

Since it's likely that this is an issue on yarns end, I'll close this. Feel free to reopen of make a comment here if you feel otherwise! :octocat:

**Comment by rkomiyama** [comment]
@quinnlangille I'm still getting the same warnings even with `npm link`. There might be an issue with `vue create`, but I'm not sure how relevant it is to this issue (https://github.com/vuejs/vue-cli/issues/1494).
