### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by NifeCz** [SSENSE/vue-carousel#306]
Hello guys,

its possible to slow down slider.. i mean time before slide and sliding time too.
Its possible to start slider on all items in same time, but not by length of array?

https://giftinbox.cz/

step 2

sorry for my english
Thank you :) 

best regards 
Karel

**Comment by quinnlangille** [comment]
Hey @NifeCz, yeah we have a `speed` prop you can pass. You can find an example of that here -> https://jsfiddle.net/quinnssense/ckd1vysd/80/

**Comment by quinnlangille** [comment]
Going to close this for now, feel free to reopen the issue or comment if you have any questions :octocat:
