### ISSUE TITLE
Touch slide is not working on touch friendly laptop

### ISSUE THREAD

**Issue by sumeshkmp** [SSENSE/vue-carousel#320]
On a touch friendly laptop, I am not able to change the slide by sliding the image. Also touch drag also seems to not working. Is it possible to change the slide on touch (not the pagination dots)?

**Comment by sumeshkmp** [comment]
Hello, Is it possible to do this ?

**Comment by quinnlangille** [comment]
No, it is not currently possible. All of our touch functionality requires `"ontouchstart" in window` to be true. If you print this in your devtools console, you'll see that only when your page is initially rendered at a mobile breakpoint will this evaluate to true. 

Adding the feature to support touch laptops would require a device agnostic way to know, in browser and on page-load, that the device is touch enabled. There are some hacks around this, but none of which are reliable enough to include in the carousel. 

As this feature is dependant on outside technology that is currently unavailable, I'll close this issue for now. If you do manage to find a solution on your end, feel free to make a PR :octocat:

**Comment by rasteiner** [comment]
For people googling, I had this problem for a "kiosk" application (a touchscreen running a fullscreen website in a museum). Fortunately you can force enable the touch events api in chrome://flags. (search for "touch api") 

Ofc this isn't a solution. Just a workaround for a very specific use case. Maybe it helps other people.
