### ISSUE TITLE
API documentation does not match Readme

### ISSUE THREAD

**Issue by caseyrlentz** [SSENSE/vue-carousel#327]
## Bug Report

**Current Behavior**
The public API documentation found on `https://ssense.github.io/vue-carousel/api/` states that the `paginationEnabled` setting is defaulted to `false`, while the Readme states otherwise.

**Possible Solution**
change `false` to `true`

**Comment by quinnlangille** [comment]
Hey @caseyrlentz, thanks for report. I'll fix right now!

**Comment by quinnlangille** [comment]
Fixed it a while ago but forgot to rebuild lol should be visible now! Thanks for reporting the issue :octocat:
