### ISSUE TITLE
Bug: VueCarousel-slide-active with perPageCustom not working correctly

### ISSUE THREAD

**Issue by dmikester1** [SSENSE/vue-carousel#338]
## Bug Report

**Current Behavior**
I am using the perPageCustom attribute to dynamically set the number of slides to either 2, 3, 4 or 5.  For some reason the VueCarousel-slide-active class only gets applied to the first 2 slides, like the number of slides is 2 all the time.

**Input Code and steps to reproduce**
`<carousel
              :navigation-enabled="true"
              :min-swipe-distance="1"
              :per-page-custom="[[0,2], [600,3], [750, 4], [1024, 5]]"
              navigation-next-label="<i class='fas fa-3x fa-angle-right'></i>"
              navigation-prev-label="<i class='fas fa-3x fa-angle-left'></i>">
              <slide
                v-for="product in products"
                :key="product.id">
                <Product
                  :id="product.id"
                  :product-info="product"/>
              </slide>
            </carousel>`

**Expected behavior/code**
The VueCarousel-slide-active class should be applied to all the slides showing no matter how many are showing.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [?]
- Node/npm version: [NPM 5.6.0]
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![capture](https://user-images.githubusercontent.com/8491610/49471425-7bfa6380-f7d2-11e8-9d2e-c1e84042531f.PNG)

**Comment by quinnlangille** [comment]
Hmm, this definitely seems like a bug. Would you be able to send a link to a fiddle or a reproduction we could debug?

**Comment by dmikester1** [comment]
Was able to modify an existing fiddle to duplicate this issue: https://jsfiddle.net/we8jbym2/

**Comment by quinnlangille** [comment]
Ok, easy enough. Looks to me as if something in the rounding logic has gone amiss - this will all be reworked in the coming v1 revamp, but it might be a while away. In the meantime, I'll add the appropriate flags and see if we can get someone to help out :octocat:

**Comment by dmikester1** [comment]
Thank you, that would be very helpful.  We are hoping to us this in a production setting.

**Comment by quinnlangille** [comment]
This has been released in 0.18.0 :octocat: Closing for now, feel free to comment if you have any more questions!
