### ISSUE TITLE
Add jest-serializer-vue

### ISSUE THREAD

**Issue by josephting** [SSENSE/vue-carousel#339]
Opening this issue as a place for discussion on this matter.

Planning to discontinue `expectToMatchSnapshot()` in [`utils.js`](https://github.com/SSENSE/vue-carousel/blob/master/tests/client/utils.js) and use [jest-serializer-vue](https://github.com/eddyerburgh/jest-serializer-vue) instead.

Below are some of my thoughts. Comments are welcome.

### Current Snapshot

```pug
exports[`Carousel should mount successfully 2`] = `
".VueCarousel-wrapper
  .VueCarousel-inner(role='listbox', style='transform: translate(0px, 0); visibility: hidden; height: auto;')
|  
.VueCarousel-pagination(style='display: none;')
  ul.VueCarousel-dot-container(role='tablist')
// 
"
`;
```

### Native Jest Snapshot

```html
exports[`Carousel should mount successfully 1`] = `"<section class=\\"VueCarousel\\"><div class=\\"VueCarousel-wrapper\\"><div role=\\"listbox\\" class=\\"VueCarousel-inner\\" style=\\"transform: translate(0px, 0); visibility: hidden; height: auto;\\"></div></div> <div class=\\"VueCarousel-pagination\\" style=\\"display: none;\\"><ul role=\\"tablist\\" class=\\"VueCarousel-dot-container\\"></ul></div> <!----></section>"`;
```

### jest-serializer-vue Snapshot

```html
exports[`Carousel should mount successfully 1`] = `
<section class="VueCarousel">
  <div class="VueCarousel-wrapper">
    <div role="listbox" class="VueCarousel-inner" style="transform: translate(0px, 0); visibility: hidden; height: auto;"></div>
  </div>
  <div class="VueCarousel-pagination" style="display: none;">
    <ul role="tablist" class="VueCarousel-dot-container"></ul>
  </div>
  <!---->
</section>
`;
```

Though, I find little to no advantage in making this change. I had hoped jest-serializer-vue to optimize the output so it's pull request friendly but it was a pretty straightforward serializer.

### What I had hoped for

This will reduce noise when reviewing pull requests with updated snapshots.

```html
<section
  class="VueCarousel"
  >
  <div
    class="VueCarousel-wrapper"
  >
    <div
      role="listbox"
      class="VueCarousel-inner"
      style="transform: translate(0px, 0); visibility: hidden; height: auto;"
    />
  </div>
  <div
    class="VueCarousel-pagination"
    style="display: none;"
  >
    <ul
      role="tablist"
      class="VueCarousel-dot-container"
    />
  </div>
</section>
```

Perhaps, a serializer with [prettier](https://prettier.io/) might be able to help. See [Sample](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAznMMCW0AEYANgIbroC8AOiAGoCucAwiQE4T2ZE0B8VU+fKgAmOAG6FS5anUYt2nOEQC0Ad1YkADprite-QYJHj87InBlEc6GACMIADxqSylGg2ZsOXZTihRdZxsAT3MZGA0odAAzCFYAWyR8CJIo0ngACgAGTQcAGnwsgEoAbnwxaxxbHCsYYKSACxxhYQQyhrgcAHMGmCSSehgIEt5UAHpRMT4BIQnxaaNJl2l3OS9FFU0SLr8SXGggurCaUXRNUnr8KGg4EZAFw1R6IlMIY5AYElsrG2diVxkHnk3iUymEEBgykgsBIfkC93Gzwe40m03GmGweCgPBAeRAEE0+yiyFAbHYqgACmwEOhkCASGIIM1cSBbBowABrOAwADKWzAfi6yAijDxvXiRAA6k14GcSGA4DyaThcBU6nSwOQWX5MKwYBSNF14iRkNESERMHiAFboBwAIXZXN5JHicAAMnDTebLSAbQ4eYLzABFegQuBei1wPFbVi6um2L6haAszSsPwwSXNGANZAADiy0fYmElGk0dNTcF1YnDeNYcAAjvQcHWDdtjRGfZh4jhhaxRSB0IG4CGwx2ox8vpnhNnkAAmPEpGqCpgQeLtlDXAIsxQAFS+tKQZsjAF9j0A).

Even though it's not exact as what I had hoped for but it will still wrap when a line exceeds the print width which seems fair to me.

**Comment by josephting** [comment]
Fair enough. I'll stick to using the existing jest-serializer-vue then.
I couldn't find any serializer with prettier support so it'll be custom if that is to be added.

**Comment by quinnlangille** [comment]
Hmmm ok cool, thanks for looking into it. Could be an interesting package to build... maybe I'll give it a shot when I have some spare time
