### ISSUE TITLE
Also on the last slide I want to get the click event of the next button.

### ISSUE THREAD

**Issue by yumemi-yamasaki** [SSENSE/vue-carousel#347]
In my application,  when the next button is clicked on the last slide,  I want to go to another page.  
But the next button does not work and ``opacity=0.5`` on the last slide, since canAdvanceForward()  is false. 
```
canAdvanceForward() {
      return this.loop || this.offset < this.maxOffset;
    },
```

I tried ``loop="true"`` and use ``@pageChange`` for page transition, however loop animation occur before page transition.

``@pageChange`` method is called when ``currentPage`` variable is changed,
so this function does not work in the last slide (when loop=false).

I want a solution for this problem in present version or want controllable method and the next button which can use also on last slide.

**Comment by quinnlangille** [comment]
Hey @yumemi-yamasaki, this has already been reported! I'll close this issue, feel free to follow along or make a comment on #345 :octocat:
