### ISSUE TITLE
vuex-router-sync peer dependency issues

### ISSUE THREAD

**Issue by samit4me** [SSENSE/vue-carousel#348]
Started getting the following peer dependency warning after upgrading from `0.9.0` to `0.16.1`. 

```
npm WARN vuex-router-sync@4.3.2 requires a peer of vue-router@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN vuex-router-sync@4.3.2 requires a peer of vuex@^2.1.0 but none is installed. You must install peer dependencies yourself.
```

After installing each version it seems this issues was introduced in version `0.12.0` due to `vue-play`, see https://github.com/SSENSE/vue-carousel/pull/266/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40.

So I assume this issue may actually lay with `vue-play` but as I still get confused with peer dependencies it would be great to get your thoughts on this? Should I open an issue with `vue-play`?

In the meantime we will stick with version `0.11.0`, currently we have:
```
"vue-router": "^3.0.2",
"vuex": "^3.0.1",
```

**Comment by quinnlangille** [comment]
Hey @samit4me, yeah these are just NPM warnings from mismatched sub-dependency versions, and probably out of our control to fix. It shouldn't cause any performance issues, and `v0.16.0` is stable to use. However, if you do notice performance problems on `v0.16.0`, feel free to open an issue!

In terms of the warnings, we'll try to resolve in `v1.0` but these sort of things are usually dependant on external factors. I'll close this for now, but will flag a reference question - you summed it up well and we get these kinds of questions a lot :octocat:
