### ISSUE TITLE
Feature Request: truncate pagination dots

### ISSUE THREAD

**Issue by Uyarn** [SSENSE/vue-carousel#356]
Hi, 
   Our team use vue-carousel and it is awesome:) 
   Does it supports hide the dots when there are too many carousel photos? 
   For example, If there are 20 photos and the current pages is 10, I just want to display the No 8, 9, 10, 11, 12 dots and hide the previous dots(1,..,7) and the following dots(13,..,20)

**Comment by quinnlangille** [comment]
Hey @Uyarn, this isn't a currently supported feature. Just to confirm, you're looking to truncate the pagination dots and show something like

`first ... 8 9 10 11 12 ... last` 

When you have more than a predetermined number of dots?

**Comment by Uyarn** [comment]
Hey @quinnlangille, thanks for your quick reply.
Yes my expectation looks like this. But actually the feature I mean is that there we can provide pagination.vue another props attribute called `dotsNumbers` which is the dot number we want to display. Of course it needs some animation to show the carousel moves.

**Comment by uyarn** [comment]
Hey @quinnlangille, thanks for your quick reply.
Yes my expectation looks like this. But actually the feature I mean is that we can provide pagination.vue another props attribute called dotsNumber which is the number of dots we want to display. Of course it needs some animation to show the move of carousel .

**Comment by quinnlangille** [comment]
Yeah, ok thats what I understood. If we pass something like `maxPaginationDotCount` we can make the logic based on that. I'll move this to a feature request and see if anyone would be interested in helping to implement!

**Comment by Uyarn** [comment]
Well, I am interested in implementing it :)

**Comment by quinnlangille** [comment]
Great @Uyarn, feel free to submit a PR once you have something up and running 🚀 If you have any questions or need a hand just lemme know!

**Comment by Uyarn** [comment]
Hi, @quinnlangille, I submit a  [PR](https://github.com/SSENSE/vue-carousel/pull/379) for this feature request :) if you are free, pleaese review it

**Comment by quinnlangille** [comment]
Hey @Uyarn, sorry for the delay! I'll hopefully be reviewing today

**Comment by quinnlangille** [comment]
This has been released! Thanks for the contribution :octocat:
