### ISSUE TITLE
Feature: stop autoplay after first interaction

### ISSUE THREAD

**Issue by shapiromichael** [SSENSE/vue-carousel#358]
**Is your feature request related to a problem?** 
When you set autoplay and drag the carousel - the autoplay will not pause / stop (there's no hover event on mobile).

**Describe the solution you'd like** 
An option to stop the autoplay after the first user interaction with the carousel (clicking on the indicator dots / navigation arrows / dragging the carousel).

**Comment by quinnlangille** [comment]
Hey @shapiromichael, this should be a pretty easy feature to implement. I think it's a reasonable request, I'll add the flags!

**Comment by parmira5** [comment]
Hey, I'm new to development and contributing to open source, but I'd love to take a shot at this.

**Comment by quinnlangille** [comment]
Hey @parmira5, I missed this notification! If you're feeling up to it feel free to take a look at our [contibution guide](https://github.com/SSENSE/vue-carousel/blob/master/CONTRIBUTING.md) and open up a PR!

**Comment by quinnlangille** [comment]
This has been released in 0.18.0 :octocat: Thanks for the contribution!

**Comment by panfanky** [comment]
The issue initially asked for "An option to stop the autoplay after the first user interaction", while now there is no option to turn this off. It would be nice in my case to restart the timeout on interaction (so it doesn't roll just after I roll manually), but not destroy it totally
