### ISSUE TITLE
Avoid using aggressive styles

### ISSUE THREAD

**Issue by hdodov** [SSENSE/vue-carousel#364]
Very nice component, but it's hard to customize it visually. I need to restyle the prev/next buttons, but it's harder because they're styled from within the component. Even worse, the styles are scoped, so they have an even bigger specificity. This sucks, especially if you're using BEM and you're writing low-specificity selectors.

I think styles should be separated and not put in the SFC. Instead, they should be in a stylesheet **with low specificity** that you can include in your app if you need them. If you don't need the default styles, you can simply not include them and set your own.

**Comment by rico-ocepek** [comment]
I did exactly what you are asking for and I  personally don't think that it was particularly difficult.
Inside the component which uses the carousel you can just use the css `/deep/` selector and as webpack (or whatever module bundler you are using) will assign the same scope attribute to everything style directive it does not actual effect the specificity of your selectors that way

`
    /deep/ .VueCarousel-navigation-button {
      top: 35%;
      border-radius: 100%;
      width: 2.5rem;
      height: 2.5rem;
      background: $primary-gradient;
      color: $white;
      font-family: 'Material Icons';
      font-size: 1.5rem;
      line-height: 0.5rem;

      &.VueCarousel-navigation-next {
        right: 0;
      }

      &.VueCarousel-navigation-prev {
        left: 0;
      }`



![image](https://user-images.githubusercontent.com/24636384/51994161-7f4b5c00-24b0-11e9-837b-6d58fe15e732.png)

**Comment by quinnlangille** [comment]
@hdodov we're actually working on a full component rewrite right now for the v1 release - this will ideally include functional components and separate styles! I'll ping here once we get to that point if you'd like to make some contributions or have any additional input :octocat:

**Comment by hdodov** [comment]
Sounds awesome! Thank you very much!

**Comment by quinnlangille** [comment]
Forgot to close this with my last comment - closing now!
