### ISSUE TITLE
Feature Request: disable pagination click but show dots

### ISSUE THREAD

**Issue by devWaleed** [SSENSE/vue-carousel#367]
Hey, is there a way to disable click on pagination so user can't click to change slide but still show pagination dots for visual understanding of the slide change?

**Comment by devWaleed** [comment]
Is there anyway to stop clicking?

**Comment by podhornyi** [comment]
For now it is impossible
But it's good to have, will create pull request with needed changes shortly

**Comment by quinnlangille** [comment]
Good idea @devWaleed. Looking forward to reviewing the PR @podhornyi

**Comment by elky** [comment]
@devWaleed you can achieve this with CSS by adding `pointer-events: none` for `.VueCarousel-pagination button`

**Comment by devWaleed** [comment]
@elky i think your solution will work
