### ISSUE TITLE
How to wrap/extend slides in a new component

### ISSUE THREAD

**Issue by emcniece** [SSENSE/vue-carousel#369]
I'd like to extend the `<slide />` component so that I can have multiple clearly-defined slide types, like `<ImageSlide />` and `<TextSlide />`. However when I attempt this, the carousel treats all of the slides as a single slide, almost as if it doesn't recognize the base `<slide />` component.

Here are some things I've tried:

0. Plain wrapper + slot (content added in parent)

```js
import { Slide } from "vue-carousel";
export default {
  name: "MySlideComponent",
  components: { Slide },
  template: `<slide><slot /></slide>`
};
```

1. Extends

```js
import { Slide } from "vue-carousel";
export default {
  name: "MySlideComponent",
  extends: Slide,
  template: `<!-- tpl & inputs here -->`
};
```

2. Mixins

```js
import { Slide } from "vue-carousel";
export default {
  name: "MySlideComponent",
  mixins: [Slide],
  template: `<!-- tpl & inputs here -->`
};
```

Parent usage:

```js
import { Carousel } from "vue-carousel";
import MySlideComponent from "./mySlideComponent.vue";
export default {
  components: {Carousel, MySlideComponent},
  name: "MyParentComponent",
  template: `<carousel><my-slide-component /><my-slide-component />...</carousel>`
};
```

The carousel renders without error and styles each slide as expected given the `perPageCustom` and `spacePadding` parameters on the carousel, but it doesn't display any navigation dots and won't drag to the next slide as if all slides are treated as one single slide.

The parent usage works fine if `<slide />` is used directly instead of `<my-slide-component />`.

Am I missing something? Is there a correct way to wrap or extend the Slide component so that it can be recognized as an actual slide?

**Comment by emcniece** [comment]
Got it. From the docs:

tagName | String | slide | Name (tag) of slide component. Overwrite with component name when extending slide component.
-- | -- | -- | --

... so using `<carousel tagName="mySlideComponent">` would work.

This behaviour is caused by the regular expressions like [Carousel.vue#L646](https://github.com/SSENSE/vue-carousel/blob/master/src/Carousel.vue#L646) which restricts the slides to child nodes matching the given `tagName`. I'm not sure why this is necessary - couldn't you assume that any top-level nodes should be slides? 

No matter, all good now.

**Comment by quinnlangille** [comment]
Hey @emcniece, we're working on a refactor of this right now for v1 - definitely a good point. We will check the need for the regex and see if it's necessary to keep!
