### ISSUE TITLE
loop return motion .

### ISSUE THREAD

**Issue by differentMonster** [SSENSE/vue-carousel#376]
Problem : isit possible that the slider can loop from the start without doing the the return back motion ?

i wish to make the slider loop from the start when reaching the end , but setting :loop="true" will have this jump back return motion which i find it disturbing , do anyone has any solution for this loop to go back smoothly from the start slider ?

**Comment by quinnlangille** [comment]
Hey @differentMonster, we already have a issue open regarding this -> #288. I'll close this in lieu of that, feel free to follow along or comment there!
