### ISSUE TITLE
Exclude CSS

### ISSUE THREAD

**Issue by willans** [SSENSE/vue-carousel#377]
Is it possible to not include the CSS that comes with the Carousel. I often like to use my own and really strip back anything I won't need.

**Comment by nicholasgriffen** [comment]
Hi willans, the style appears to be baked into the component, as for example from line 910 here https://github.com/SSENSE/vue-carousel/blob/master/src/Carousel.vue. I suppose you could clone, remove the styles from the source code, and build an unstyled version for your project but I do not know how that would affect the behavior of the Carousel.

**Comment by quinnlangille** [comment]
@nicholasgriffen is correct! We're currently using single file components, so the template and styles are baked in. Part of our v1 refactor is to move to a more functional component design, which will have the added benefit of separating our CSS.

Going to close this in the mean time, as currently we have no way around embedded CSS.
