### ISSUE TITLE
Bug: `pageChange` event isn't triggered in in-dom template.

### ISSUE THREAD

**Issue by murmur76** [SSENSE/vue-carousel#38]
Currently, camel case named event is not triggered in in-dom template.
Maybe we need to change the event name like `page-change` or trigger both events.

Refer https://github.com/vuejs/vue/issues/4044

**Comment by toddlawton** [comment]
I'll make sure to document this at some point, but much like @yyx990803's stance on in-dom templates, I'd prefer to advocate using string templates or standalone components as they're much more stable in the Vue ecosystem. Cheers!
