### ISSUE TITLE
Auto hide swal when slideclick

### ISSUE THREAD

**Issue by sun-kingcity** [SSENSE/vue-carousel#393]
## Bug Report

**Current Behavior**
When bind click to trigger a swal, the popup turn on and turn off immediately

```
      <slide
        data-index="0"
        data-name="MySlideName"
        @slideclick="showAlert">
        slide content
      </slide>




  methods: {
      showAlert(dataset){
        var app = this;
        app.$swal('Hello Vue world!!!');
          // setTimeout(function(){
          //   app.$swal('Hello Vue world!!!');
          // },1);
      }
  }
```

**Possible Solution, it's ok if adding 1ms timeout (tried nextTick, but no luck)**
```

  methods: {
      showAlert(dataset){
        var app = this;
           setTimeout(function(){
             app.$swal('Hello Vue world!!!');
           },1);
      }
  }
```

**Comment by quinnlangille** [comment]
Hey @sun-kingcity, this bug doesn't seem related to the vue-carousel's code base. and more an issue with it's implementation. I'll close this for now, so someone doens't interpret it as needing fixed.
