### ISSUE TITLE
Last slide is getting cropped in carousel

### ISSUE THREAD

**Issue by SushmitaTardia** [SSENSE/vue-carousel#397]
## Bug Report

**Current Behavior**
On sliding to last slide, there is a truncation on the last slide

**Input Code and steps to reproduce**
- https://jsfiddle.net/705fwdta/

**Expected behavior/code**
There should be no truncation on the last slide.

**Comment by quinnlangille** [comment]
Hey @SushmitaTardia, I'm not seeing any cropping of the slide in your example. If I'm understanding correctly, you're seeing the 5th slide appearing less wide than the 4th slide, when on the 3rd page?

**Comment by SushmitaTardia** [comment]
![Screen Shot 2019-03-25 at 1 44 00 PM](https://user-images.githubusercontent.com/36231806/54904272-17d7e880-4f04-11e9-8321-29c61f01acaa.png)
Hey,
Thank you for your reply,
I am attaching the screenshot. You can see that the 5th slide is cropped( the label "5" is cropped).

**Comment by quinnlangille** [comment]
Hey @SushmitaTardia, this just seems to be an issue with the CSS you've added. If you uncomment the transform you have above it works as expected. As this doesn't seem related to the carousel, I'll close this issue. Thanks for reporting, if you have any questions in the future feel free to open another issue!
