### ISSUE TITLE
Bug: Syntax error when running 'yarn dev'

### ISSUE THREAD

**Issue by ElijahKotyluk** [SSENSE/vue-carousel#405]
I'm trying to run the application using `yarn dev`, and I was coming an error compiling.
 
ERROR in ./play/index.js
Module build failed: SyntaxError: Unexpected token (252:2)

    250 |   })
    251 |   .add("With local event on pageChange", {
    252 |   .add("navigation-click event", {
        |   ^
    253 |     template:
    254 |        `<div style="width: 100%; display: flex; justify-content: center; margin-top: 40px;">
    255 |         <carousel style="width: 500px;" @navigation-click="onNavigationClick" 
                                       navigationEnabled :paginationEnabled="false">`

When I went to line 252, it turns out line 251 doesn't close at any point. So just to see what happened I removed line 251 `.add("With local event on pageChange", {`, then the same error appeared about 50 lines down. I took the same approach and everything is running/working. 

ERROR in ./play/index.js
Module build failed: SyntaxError: Unexpected token (300:2)

    298 |   })
    299 |   .add("With local event on pageChange", {
    300 |   .add("pageChange event", {
        |   ^
    301 |     template:
    302 |       `<div style="width: 100%; display: flex; justify-content: center; margin-top: 40px;">
    303 |         <carousel style="width: 500px;" @pageChange="onPageChange">`

**Comment by quinnlangille** [comment]
Hey @eladFrizi, good call this seems to be the result of a bad merge. Strange it didn't get caught in QA.. I'll fix ASAP!

**Comment by quinnlangille** [comment]
This should be resolved now, thanks for reporting @ElijahKotyluk! :octocat:
