### ISSUE TITLE
Can't Drag or Swipe Left on Firefox

### ISSUE THREAD

**Issue by stelli98** [SSENSE/vue-carousel#410]
Vue carousel is perfectly working on chrome. But when we try on firefox, it only can be drag or swipe to right, when we want to swift to left, the carousel didn't move at all.

 I use vue carousell 0.6.5, and already change it to 0.18 
but the issue still happen. 

i also try to use **:navigationEnabled="true"** and try to navigate to the left, using the arrow and it's working, but it didn't work if i use mouse drag

**Comment by quinnlangille** [comment]
Hey @stelli98, thanks for reporting! We have a similar thread here #412. I'll close your issue as a duplicate, but feel free to comment and follow along at #412 :octocat:
