### ISSUE TITLE
Is there a "destroy" method for this carousel?

### ISSUE THREAD

**Issue by kkolataj** [SSENSE/vue-carousel#414]
I would like to destroy carousel with method if its possible because on mobile i need slides placed in vertical view. In this case i just want to use styled list.

I created my project in vue.

Kind regards Reaviel

**Comment by quinnlangille** [comment]
Hey @kkolataj, every Vue component has a built in destroy method as part of their lifecycle. Calling `Carousel.destroy()` will do just that! Although, keep in mind we have some custom functionality in destroy (most notably, removing event listeners) which you'll need to reattach if you still want for any reason.

I'll close this now, as it feels pretty resolved. Feel free to comment below if you have any additional questions!
