### ISSUE TITLE
Issue with emitting transitionstart and transitionend events

### ISSUE THREAD

**Issue by wolfrstrudel** [SSENSE/vue-carousel#418]
## Bug Report

**Current Behavior**
Currently the transitionstart and transitionend events emit on all transitions on the carousel and its children. For example, the components within my slides have their own transitions on hover and this causes both of the carousel transition events to fire. Perhaps this is intended behavior but I thought it would only be related to the carousel transitioning between pages/slides. 

**Possible Solution**
A possible solution would be to check if the event target is the carousel itself before emitting the events.

**Comment by quinnlangille** [comment]
Hey @wolfrstrudel, this seems related to #409. I'm going to rename that and we can pick up the discussion for all event propagation related bugs there!
