### ISSUE TITLE
Bug: extra blank page

### ISSUE THREAD

**Issue by irhamkim** [SSENSE/vue-carousel#42]
I'm trying to copy from one of the example fiddle, however I'm encountering an issue where the pagination and carousel showing extra blank page(s).

here's the fiddle
https://jsfiddle.net/irhamkim/dqwbjkre/1/

**Comment by toddlawton** [comment]
Hey @irhamkim, thanks for filing the issue. I investigated and the issue was fixed in a previous release but the version of vue-carousel referenced in the jsfiddle was out of date. I updated the version and your fiddle appears to work properly now.

Cheers!
