### ISSUE TITLE
Improve Website's Examples and API

### ISSUE THREAD

**Issue by rochabianca** [SSENSE/vue-carousel#420]
I have the habit to always check the website first and then the github, and have notice that the github documentation is way to more detailed than the website, so, could we improve it?

There is some things that people would like to use, that is available (like customize the prev and next arrow, like you can see here: https://github.com/SSENSE/vue-carousel/issues/88#issuecomment-370428489) would be nice to be a example of that on the website

And also a part for API events bellow the global config like it is on the documentation

Tell me what do you think about it :)

**Comment by quinnlangille** [comment]
Hey @rochabianca totally agree, we're in the middle of a pretty substantial api-recator for v1.0 0 - it will be accompanied with new documentation! We have an open issue here to track the progress once we start #262! I'll close this for now, but thanks for the comment. If you have any suggestions about the docs, feel free to post them on #262 :octocat:

**Comment by rochabianca** [comment]
Oh @quinnlangille It's great to know this ! If I have any new ideas I will post there :D
