### ISSUE TITLE
only one element slide

### ISSUE THREAD

**Issue by valeriy-efimov** [SSENSE/vue-carousel#421]
Is it possible to customize your plugin so that when switching slides only one element is added.
example
![image](https://user-images.githubusercontent.com/5989188/56030637-ffe6ce00-5d25-11e9-95e8-b52dedc33548.png)
i want this
![image](https://user-images.githubusercontent.com/5989188/56030661-12f99e00-5d26-11e9-9ea1-8a23a37a8079.png)

**Comment by quinnlangille** [comment]
Hey @valeriy-efimov, you can set the perPage prop to 1! https://ssense.github.io/vue-carousel/api/#perPage

**Comment by valeriy-efimov** [comment]
@quinnlangille not working
https://jsfiddle.net/suobpda2/
if press right button, display  "3 5 6" but i want to see "2 3 4" if again press "3 4 5" etc

**Comment by quinnlangille** [comment]
Ah I misunderstood your request, for that you'll need to add `scrollPerPage=false`, like this -> https://jsfiddle.net/oLvr8wem/

**Comment by valeriy-efimov** [comment]
@quinnlangille thank you very much!

**Comment by Jesus82** [comment]
Hi @quinnlangille while this visually works, it is not possible to target the "active" sliders this way. 

When you go from "items 1-2-3" to "items 2-3-4", active classes switch from "items 1-2-3" to " items 4-5-6", so when you visually get to "items 4-5-6" you don't have any active class anymore.

![image](https://user-images.githubusercontent.com/8875832/72601420-ab582b00-3915-11ea-9416-3bdcba3bf16e.PNG)

Is there any workaround to that? 

Thanks!
