### ISSUE TITLE
 Carousel doesn't display until I click on where the slide would be

### ISSUE THREAD

**Issue by phuclh** [SSENSE/vue-carousel#425]
I am using `"vue-carousel": "^0.18.0",` and Carousel doesn't display until I click on where the slide would be. I were looking for the answers and I believe that @quinnlangille said this issue already fixed in the recent update. But it is still happening for my case. Below is my code.

Here is my code:
```
<template>
<carousel :perPage="4" :navigationEnabled="true" :paginationEnabled="false">
                <slide v-for="(product, i) in products" :key="i" class="w-full md:w-1/4 px-3">
                    <product-item :key="i" :product="product"></product-item>
                </slide>
            </carousel>
</template>

<script>
    import ProductItem from './ProductItem';
    import {mapGetters, mapActions} from 'vuex'
    import {Carousel, Slide} from 'vue-carousel';

    export default {
        computed: {
            ...mapGetters({
                products: 'product/bestseller',
            })
        },
        mounted() {
            this.$store.dispatch('product/getProducts', 'bestseller');
        },
        components: {
            ProductItem,
            Carousel,
            Slide
        }
    }
</script>
```

ProductItem component:

```
<template>
    <div class="bg-white border border-transparent hover:border-gray-200 p-3 mb-3 group relative h-auto">
......
</div>
</template>

<script>
    export default {
        props: ['product']
    }
</script>
```

**Comment by quinnlangille** [comment]
Hey @phuclh, yeah we fixed an issue related to this a few versions ago! Your code looks fine, so mind sending a working reproduction of the issue on a jsFiddle or else so we can debug further? Thanks! :octocat:

**Comment by rishabhgoel9797** [comment]
Its happening with me too. I am using 0.6.5. Please help

**Comment by quinnlangille** [comment]
@rishabhgoel9797 this issue was fixed after 0.6.5, so you'll need to upgrade

**Comment by phuclh** [comment]
@quinnlangille I already fixed, it conflicted with tailwind grid, I just simple removed tailwind classes and used the default grid of this plugin.

I have another question. Is it possible to make the vertical carousel? I tried to find some options, but there was nothing that related to that. Thank you.

**Comment by quinnlangille** [comment]
Hey @phuclh, we currently don't support a vertical carousel, we've talked about it in a few issues in the past but adding it isn't in the immediate roadmap.

Also, thanks for reporting in that this issue is in fact resolved, I'll close this now!
