### ISSUE TITLE
Show two lines of images and show hidden layer with description text when clicking on the image

### ISSUE THREAD

**Issue by amrigo** [SSENSE/vue-carousel#429]
Hi, 
I already install and setup vue-carousel and it´s just fine.

I am looking to use vue-carousel having two rows of images, let´s say 4 images in the above row and 4 images in the below row. 

And when clicking in one image it shows a div with some description text, accepting html tags to allow having links. 

Is it possible today ? if so wich configuration options must i change ?

**Comment by quinnlangille** [comment]
Hey @amrigo, this has been mentioned a few times in previous comments and it's currently not possible. We're planning on adding some customizable slots to the slide elements as part of our v1 refactor, however! The refactor is in progress now, so stay tuned! Will close this for now as we don't have any solution for v0 planned :octocat:
