### ISSUE TITLE
Vue carousel looks unusual until clicked on side

### ISSUE THREAD

**Issue by rishabhgoel9797** [SSENSE/vue-carousel#430]
See how the carousel looks until i clicked on side. Please rectify this soon
![Screenshot 2019-04-18 at 6 36 28 PM](https://user-images.githubusercontent.com/22225114/56363168-341c2c00-6209-11e9-9ffe-0baa1576c076.png)

**Comment by quinnlangille** [comment]
Hey @rishabhgoel9797, what version of the carousel are you using? What browser is the occurring in? Can you send a reproduction via JSfiddle?

**Comment by rishabhgoel9797** [comment]
I am using 0.6 version. Using in chrome.

**Comment by quinnlangille** [comment]
@rishabhgoel9797 0.6 is 12 minor versions behind our current release, I'd suggest upgrading and see if that helps out

**Comment by rishabhgoel9797** [comment]
I am using ^0.6.5. Since the latest version is not updated in node. can you help me with the latest version

**Comment by quinnlangille** [comment]
if you run `npm install vue-carousel@latest` or `npm install vue-carousel@0.18.0` you'll install the latest version

**Comment by rishabhgoel9797** [comment]
`<carousel
          per-page="4"
          loop=true
          pagination-size=0
          :navigation-enabled="Object.keys(cardSegments).length>4"
          :navigation-prev-label="prevLabel"
          :navigation-next-label="nextLabel">
          <slide v-for="card in cardSegments" :key="card.id"> 
            <Card :sample="sample" /> 
          </slide>
        </carousel>`

I guess there should be nothing to do with CSS. Please help me in rectifying it

**Comment by rishabhgoel9797** [comment]
@quinnlangille what i should do in this case. Please let me know as we want to move this in production

**Comment by quinnlangille** [comment]
Hey @rishabhgoel9797, you've upgraded your version to our latest and you're still getting this issue?

**Comment by rishabhgoel9797** [comment]
Yes , I am now using version 0.18. can you send any fiddle or codepen to
show gallery type of implementation?

**Comment by rishabhgoel9797** [comment]
Hey @quinnlangille . I just figured out that if i am doing that with static data its working fine. But when i am loading from backend. Its behaving like this

**Comment by thibaultchazal** [comment]
I'm having quite the same issue.
Nothing is displayed until I clicked or an event is fired in the component.

Also, if any variable changed in my component, the carousel start again from the beginning. Maybe it comes from the same thing.

I have the last version.

**Comment by rishabhgoel9797** [comment]
It worked. It was a flex issue for me

**Comment by thibaultchazal** [comment]
Okay. Can you explain a little bit more if it is relevant and close the issue ?
I start a new issue https://github.com/SSENSE/vue-carousel/issues/435

**Comment by quinnlangille** [comment]
Yeah @thibaultchazal I'll close this and we can continue on your issue, seems like it might be different cause
