### ISSUE TITLE
Content of slide not displayed and carousel restart at events

### ISSUE THREAD

**Issue by thibaultchazal** [SSENSE/vue-carousel#435]
## Bug Report

**Current Behavior**
The image inside the slide is not displayed. Only the bottom dots.
The image is only displayed when something happens : a click in the DOM, a variable change, etc...

Also, when a variable change, it restart the carousel.

**Input Code and steps to reproduce**
This carousel is inside a vuetify stepper and is not on the first step.

```js
        <carousel
          :per-page="1"
          autoplay
          :autoplayHoverPause="true"
          :autoplayTimeout="timing"
          :navigateTo="[0, start]"
        >
          <slide
            v-if="pictures"
            v-for="(picture,i) in pictures"
            :key="i"
          >
            <v-img class="diapo" :src="picture.link" />
          </slide>
        </carousel>
        <v-btn
          :disabled="disable"
          v-on:click="restart()"
        >
          À moi
        </v-btn>
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Environment**
- Babel version(s): 7.2.2
- Babel loader 8.0.4
- VUE 2.5.21
    "node": "= 8.10.0",
    "npm": "= 6.9.0"

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by quinnlangille** [comment]
Hey @thibaultchazal, sorry about the delay here. Are you trying to render server side or is this on the client?

**Comment by thibaultchazal** [comment]
Hi @quinnlangille, thanks for your answer but I have had to choose an other solution for my carousels.
Anyway, I was trying to render client side.
