### ISSUE TITLE
Feature: Add class 'active' to set the active slide

### ISSUE THREAD

**Issue by kenyk7** [SSENSE/vue-carousel#44]

**Comment by mystrdat** [comment]
Not a class, there should be an API to get/set the active slide, ideally even the progress of the swipe motion. The lack of it makes this plugin useless to me, so +1.

**Comment by dieguezz** [comment]
I think there should be a class as well for better style customization

**Comment by Aterr** [comment]
Any news on this one ?

**Comment by quinnlangille** [comment]
Hey guys, forgot to update this issue - we added this feature a while ago, and there are .slide-active and .slide-center classes added to visible slides!
