### ISSUE TITLE
Bug: Adjustable height breaks carousel on Firefox

### ISSUE THREAD

**Issue by hjbdev** [SSENSE/vue-carousel#446]
## Bug Report

**Current Behavior**
On Firefox, when the prop adjustableHeight is set to true, the slides are overlayed on top of each other.

**Input Code and steps to reproduce**
https://codesandbox.io/s/vue-template-dpjk7

**Expected behavior/code**
The slides appear next to each other side by side, as seen in Chrome/Chromium browsers

**Environment**
- Laravel Mix 4.0.15
- Node/npm version: npm 6.4.1 node 8.12
- OS: Ubuntu 18.04.2 LTS

**Possible Solution**
The issue seems to revolve around `display:table` on the class `.VueCarousel-slide-adjustableHeight`. However removing this property breaks the adjustableHeight functionality.

**Comment by quinnlangille** [comment]
Ah really good catch @HJBDev, I'll flag this as a bug!

**Comment by quinnlangille** [comment]
Actually scratch that, we have another open issue for this same problem here -> #412 

I'll close this and we can continue any conversation there :octocat:
