### ISSUE TITLE
Custom forward/next-slide button?

### ISSUE THREAD

**Issue by ckhatton** [SSENSE/vue-carousel#513]
I have created a standalone button on the slide. How does one trigger a slide change forward?

Currently I have created a method, but it breaks the order of the slides:

    const first = this.slides.shift()
    this.slides = this.slides.concat(first)

:octocat:

**Comment by lazehang** [comment]
Reference the carousel and call its handleNavigation method.

for eg:
```
next() {
 this.$refs.carousel.handleNavigation()
},

prev() {
 this.$refs.carousel.handleNavigation('backward')
}
```

note: your carousel component should have ref attribute set to 'carousel' for this example

**Comment by ckhatton** [comment]
You legend!! ⭐️ Thank you

![bitmoji](https://render.bitstrips.com/v2/cpanel/3ea5fb70-e76c-4c70-99c8-c7ba6f2d9b5b-9f1d074d-fa47-40f6-8912-920d9a68165e-v1.png?transparent=1&palette=1&width=246)
