### ISSUE TITLE
DO NOT USE THIS!!!!!!

### ISSUE THREAD

**Issue by tircomnicu** [SSENSE/vue-carousel#520]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Input Code and steps to reproduce**
- You can add a link to a hosted repo, or a JSfiddle, repl.it, etc here
- Or, you can paste your code in a formatted block like so:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by flyingL123** [comment]
@tircomnicu why not?

**Comment by roni-estein** [comment]
@tircomnicu I don't understand this issue.

**Comment by cmitchell-rms** [comment]
lol wut

**Comment by tircomnicu** [comment]
Wow, my apologies, wasn't me who wrote this issue, sorry.

The plugin is working great, I used it on multiple projects.
You can close this issue.

I'm so sorry about this.
