### ISSUE TITLE
navigationNextLabel and navigationPrevLabel don't work

### ISSUE THREAD

**Issue by stivenramireza** [SSENSE/vue-carousel#522]
## Bug Report

**Current Behavior**
I'm currently working in a project using this vue-carousel component, but labels in navigation don't appear. So, there is not way to navigate to other slides.

Any solution?

**Comment by JeromeSaby** [comment]
It should work like this : 
`<carousel :navigation-enabled="true">`

**Comment by Paulsky** [comment]
@stivenramireza I don't want to be rude, but did you check your CSS? I had the same problem, but one of my parent elements had the overflow: hidden; style. Removing this fixed the displaying issue.

**Comment by stivenramireza** [comment]
> @stivenramireza I don't want to be rude, but did you check your CSS? I had the same problem, but one of my parent elements had the overflow: hidden; style. Removing this fixed the displaying issue.

It was my CSS. Thanks!
