### ISSUE TITLE
Modal Functionality

### ISSUE THREAD

**Issue by tdrach** [SSENSE/vue-carousel#53]
I'm not sure if any Modal-like functionality is planned for the future of this project, but thought I'd try and discuss here. Much of the time I use image carousel functionality, I also want to use the same carousel to prompt a modal, with content of the image, and anything else in the `<slot>`. Not dissimilar to viewing a photo on Facebook.

The modal could be prompted by:
- "Selecting" or clicking the image
- "Selecting" an `expand` icon, or similar
- etc... 

Is this something that may be planned for a the project? 

Are there specific avenues you'd like to take in order to implement something like this? 

If it is planned, would a PR be welcomed?

**Comment by mystrdat** [comment]
That sounds way overfeatured for the usecase, I don't see why you couldn't connect it to a standalone modal library.

**Comment by tdrach** [comment]
Fair point! I'll keep it up in a fork 👍
