### ISSUE TITLE
Navigation click buttons ouside of the carousel

### ISSUE THREAD

**Issue by Shindraela** [SSENSE/vue-carousel#558]
Hello,

I don't know if it was already asked (I've searched throw the issues and read the doc) but is there an option for creating custom navigation click buttons outside of the carousel ?
As you can see on the screenshot, I would like to remove navigation click buttons from both side of the carousel and put them outside on the top.

<img width="1440" alt="Capture d’écran 2021-01-20 à 18 24 46" src="https://user-images.githubusercontent.com/17910279/105212239-82343100-5b4d-11eb-8f9e-22d988ad67ef.png">

Thank you.

Ok I've just changed the navigation button position with CSS, sorry for this issue.

**Comment by dsantanac** [comment]
<template>
...
    <carousel ref="car"> 
    ...
    </carousel>
...
<button @click="nextPage' />
</template>


<script>
    methods: {
        nextPage(){
            this.$refs.car.handleNavigation('forward');
        }
</script>

**Comment by dsantanac** [comment]
\<carousel ref="car">
...
\</carousel>
..

\<script>
    methods: {
        nextPage(){
            this.$refs.car.handleNavigation('forward');
        }
\</script>`
