### ISSUE TITLE
How has been looping

### ISSUE THREAD

**Issue by wjl388** [SSENSE/vue-carousel#59]
Thank you want to and I said as soon as possible

**Comment by renanpro03** [comment]
There's no looping yet?

**Comment by esemusa** [comment]
```javascript
<carousel :loop="true">
...
</carousel>
```

**Comment by watzon** [comment]
The loop option needs to be documented

**Comment by quinnlangille** [comment]
@watzon I'll make a note to add the :loop feature into the docs
