### ISSUE TITLE
Doesn't run with vue-webpack-boilerplate

### ISSUE THREAD

**Issue by pushamaku** [SSENSE/vue-carousel#6]
Running:

node v6.8.1
npm v4.0.5

Setup a vue boilerplate with vue-cli:

>npm install -g vue-cli
>vue init webpack test
>cd test
>npm install
>npm install -S @ssense/vue-carousel

Added to main.js:

```javascript
import VueCarousel from '@ssense/vue-carousel'
Vue.use(VueCarousel)
```
However I always get this error when I run with **npm run dev**:

>
>Uncaught SyntaxError: Unexpected token import
>    at Object.<anonymous> (app.js:642)
>    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
>    at eval (eval at <anonymous> (app.js:660), <anonymous>:11:20)
>    at Object.<anonymous> (app.js:660)
>    at __webpack_require__ (app.js:556)
>    at fn (app.js:87)
>    at Object.<anonymous> (app.js:587)
>    at __webpack_require__ (app.js:556)
>    at app.js:579

*(app.js:642)*
```javascript
eval("import Carousel from './Carousel.vue';\nimport Slide from './Slide.vue';\n\nconst install = (Vue) => {\n  Vue.component('carousel', Carousel);\n  Vue.component('slide', Slide);\n};\n\nexport default install;\n\nexport {\n  Carousel,\n  Slide,\n};\n\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9+L0Bzc2Vuc2UvdnVlLWNhcm91c2VsL3NyYy9pbmRleC5qcz8wNTY4Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7O0FBRUE7QUFDQTtBQUNBO0FBQ0EiLCJmaWxlIjoiOS5qcyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCBDYXJvdXNlbCBmcm9tICcuL0Nhcm91c2VsLnZ1ZSc7XG5pbXBvcnQgU2xpZGUgZnJvbSAnLi9TbGlkZS52dWUnO1xuXG5jb25zdCBpbnN0YWxsID0gKFZ1ZSkgPT4ge1xuICBWdWUuY29tcG9uZW50KCdjYXJvdXNlbCcsIENhcm91c2VsKTtcbiAgVnVlLmNvbXBvbmVudCgnc2xpZGUnLCBTbGlkZSk7XG59O1xuXG5leHBvcnQgZGVmYXVsdCBpbnN0YWxsO1xuXG5leHBvcnQge1xuICBDYXJvdXNlbCxcbiAgU2xpZGUsXG59O1xuXG5cblxuLy8vLy8vLy8vLy8vLy8vLy8vXG4vLyBXRUJQQUNLIEZPT1RFUlxuLy8gLi9+L0Bzc2Vuc2UvdnVlLWNhcm91c2VsL3NyYy9pbmRleC5qc1xuLy8gbW9kdWxlIGlkID0gOVxuLy8gbW9kdWxlIGNodW5rcyA9IDAiXSwic291cmNlUm9vdCI6IiJ9");

```
Any help would be appreciated :)

**Comment by toddlawton** [comment]
Hi, @pushamaku, thanks for leaving a detailed ticket!

The issue you're experiencing has been fixed in [0.4.3](https://github.com/SSENSE/vue-carousel/tree/0.4.3). I've verified the fix with vue-webpack-boilerplate using the steps outlined above.
