### ISSUE TITLE
Displaying a popup is hidden by overflow property

### ISSUE THREAD

**Issue by ShaunEgan** [SSENSE/vue-carousel#60]
I am probably doing something wrong - I am really new to the front-end world.

I am trying to display a div using `v-if`. The `ViewCarousel-Wrapper` class specifies `overflow: hidden;` - which typically cuts off most of my popup.

Is there a recommended / suggested way to deal with this?

**Comment by HelgeSverre** [comment]
@ShaunEgan  Try the Vue portal plugin to render the modal outside of the carousel slider.

**Comment by quinnlangille** [comment]
Hadn't seen this issue before, and it's pretty old. I'd say @HelgeSverre's solution is acceptable, going to close this! If anyone has any problems relating to this, feel free to comment here or open a new issue :~)
