### ISSUE TITLE
Feature Request: Create prop to add margin between elements

### ISSUE THREAD

**Issue by Jorjon** [SSENSE/vue-carousel#68]
I'm increasing horizontal margin on `VueCarousel-slide`, but the carousel is being cut off.

![image](https://user-images.githubusercontent.com/796966/28575491-725c7558-7127-11e7-9b50-a20b9d88f51f.png)

I can set `flex-basis` manually but it doesn't get updated with resolution changes.

```<template>
  <carousel :perPage="5" :navigationEnabled="true" :paginationEnabled="false">
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
    <slide>
      <img src="http://via.placeholder.com/300">
    </slide>
  </carousel>
</template>

<script>
import { Carousel, Slide } from 'vue-carousel';

export default {
  components: {
    Carousel,
    Slide,
  },
};
</script>

<style lang="scss">
  $margin: .5%;
  $padding: 1%;

  .VueCarousel-inner {
    /*flex-basis: 327px !important;*/
  }

  .VueCarousel-slide {
    margin: 0 $margin 0 $margin;
    padding: $padding $padding $padding $padding;
    border: 2px solid #0e5a7e;

    img {
      width: 100%;
    }
  }

  .VueCarousel-navigation-button {
    color: inherit !important;
  }
</style>
```

**Comment by glutaminefree** [comment]
I want margin between slides too!

**Comment by codenamics** [comment]
up

**Comment by quinnlangille** [comment]
Hey guys, we actually do have a `spacePadding` prop that adds padding between slides. I'm aware it's not the same, but it can achieve a similar look if that's all that's required. Otherwise adding the margin would be easy enough, will just need someone to submit the PR! 

I'll make this as a good first feature to try and get some traction

**Comment by markus361** [comment]
> to add some space on each slide, i added on css 8px padding left/right on each slide

@CavalcanteLeo, did you encounter a bug in IE11? I tried to do the same an but slides don't fit the slider width anymore

**Comment by KaragiannidesAgapios** [comment]
@markus361 Maybe a bit late to answer but I had the same issue. I check this [thread](https://github.com/philipwalton/flexbugs/issues/3), understand the problem and my solution was, this one: 

> if feasible, do not apply padding or border directly to a flex child. Allow the flex child to be a containing element to another element that will receive the padding or border. This is somewhat undesirable because avoiding this sort of extra markup is one the big benefits of box-sizing:border-box;.

```
        .VueCarousel-slide > div {
            padding-left: 15px;
            padding-right: 15px;
        }
```

This solved the problem for me.

**Comment by lamoquette** [comment]
up please

**Comment by Torone** [comment]
Guys, use padding instead...

**Comment by lerik1408** [comment]
In the slide tag, make a wrap and set it to padding : 0 10px;

**Comment by oroojtatiev** [comment]
with padding is bool sheet

**Comment by rafikmoreira** [comment]
Has it not been implemented?

**Comment by oza75** [comment]
@KaragiannidesAgapios proposition solved my issue too.

**Comment by OctopussyO** [comment]
up

**Comment by CavalcanteLeo** [comment]
Stop using this lib.

It's full of bugs, and it's abandoned.

Use this instead:
https://gs-shop.github.io/vue-slick-carousel/#/
