### ISSUE TITLE
Compile library

### ISSUE THREAD

**Issue by Jorjon** [SSENSE/vue-carousel#69]
I'm trying to recompile the library in order to change some functionality, and these are the commands I ran:
```
npm install
npm run build
```
But I get this message:

```
> vue-carousel@0.6.5 build ...\node_modules\vue-carousel
> webpack --config config/webpack.min.conf.js && npm run updateDocAssets

Hash: 418ca0cfdee1742e1365
Version: webpack 1.15.0
Time: 58ms
              Asset     Size  Chunks             Chunk Names
vue-carousel.min.js  2.12 kB       0  [emitted]  main
    + 1 hidden modules

ERROR in vue-carousel.min.js from UglifyJs
SyntaxError: Unexpected token: name (Carousel) [vue-carousel.min.js:62,8]
```

It seems it doesn't compile .vue files. Is there a way to achieve that?

Thanks

**Comment by quinnlangille** [comment]
Hey @Jorjon, sorry for the late reply here. I'm building find on the newest version (0.6.7) maybe try updating and running build again.

**Comment by quinnlangille** [comment]
Haven't heard back here so going to close this, feel free to open a new issue if you're still having a problem :~)
