### ISSUE TITLE
Question: is there any attribute to remove navigation dots?

### ISSUE THREAD

**Issue by Developerlopez** [SSENSE/vue-carousel#70]
I want remove just the navigation dots and use only the next and prev buttons.

**Comment by aroy314** [comment]
The only way I found is with css
`.VueCarousel-pagination {
    display: none;
}`

**Comment by andreasvirkus** [comment]
You can pass `:paginationEnabled="false"` to your `carousel` component.

```html
<carousel :autoplay="true" :autoplayTimeout="2000" :paginationEnabled="false">
```

**Comment by jezmck** [comment]
https://ssense.github.io/vue-carousel/api/#paginationEnabled
(deep link not actually working at present)

**Comment by esemusa** [comment]
```javascript
<carousel :paginationSize=0>
..
</carousel>
```

**Comment by quinnlangille** [comment]
@Developerlopez were any of these answers able to help you out?

**Comment by prabshah** [comment]
Does anyone know how can I disable the title being appeared when I hovered over the dots?

`:paginationEnabled="false"` removes the whole pagination from the carousel but I only want to stop the title being shown when hovered over the pagination dots. I looked at the docs but have not found the solution.

**Comment by rafeeque-cairs** [comment]
https://github.com/SSENSE/vue-carousel/issues/208#issuecomment-614474833
