### ISSUE TITLE
:navigationNextLabel='something' doesn't work 

### ISSUE THREAD

**Issue by JeromeDevillers** [SSENSE/vue-carousel#74]
Hello , 

This parameter seems doesn't work : 

**:navigationNextLabel='test'**

Any issue or I use it in the wrong way ? I also declare :navigationEnabled to True.

Thank you.

**Comment by JeromeDevillers** [comment]
I find a css alternative, i put a property visibility: hidden to the element then i create a :before element on this selector set attribute : content : " " and put visibility: visible.

**Comment by rolandsaven** [comment]
@JeromeDevillers HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should use "navigation-next-label" instead of "navigationNextLabel".

**Comment by lucassanchez** [comment]
To me not work and I need to use css too: 

```
.VueCarousel-navigation-button {
    text-indent: -1000em;
}

.VueCarousel-navigation-button::before {
    content: "";
    position: absolute;
    top: 8px;
    height: 23px;
    width: 16px;
}

.VueCarousel-navigation-next::before {
    background: url('public/svgs/next.svg');
    right: 6px;
}

.VueCarousel-navigation-prev::before {
    background: url('public/svgs/prev.svg');
    left: 6px;
}

```

**Comment by quinnlangille** [comment]
@rolandsaven is correct here, in that you should be using dash-case alternatives to the camelCased props. Going to go ahead and close this issue, feel free to open a new issue as a bug report if you're still having trouble
