### ISSUE TITLE
How can I get the current index?

### ISSUE THREAD

**Issue by hhlingyoko** [SSENSE/vue-carousel#80]
How can I get the current index?
Can you add  a function  to return the current index?

**Comment by runxc1** [comment]
Did you find out how to get or set the index?

**Comment by esemusa** [comment]
`computed: {
      currentIndex: {
        cache: false,
        get() {
          return this.$refs.carousel ? this.$refs.carousel.currentPage : 0;
        }
      }
    }`

**Comment by esemusa** [comment]
try to add;

```
cache: false
```

**Comment by deepakkabbur** [comment]
```
computed: {
   ...mapGetters({...}),
  currentIndex: {
        cache: false,
        get () {
          return this.$refs.carousel ? this.$refs.carousel.currentPage : 0
        }
      }
}
```
No luck :(
`this.$refs.carousel ` is `undefined`

**Comment by Udobnaja** [comment]
In your template
`<carousel v-on:pageChange="pageChange">...</carousel>`
In your script 
`methods: {
    pageChange(i){
                console.log('current Index', i);
   },
}`

**Note:**  It fired when you change current page (by navigation or pagination)

**Comment by Udobnaja** [comment]
@hhlingyoko, please, close this issue
