### ISSUE TITLE
Dont see images after toggling a component with v-show

### ISSUE THREAD

**Issue by ianengelbrecht** [SSENSE/vue-carousel#85]
I have the carousel inside a component that is hidden at startup using v-show. When I toggle the component on, the carousel is there but the images do not show. I first have to scroll the carousel, and then the images appear. Each slide is using a child component which has the image as well as some functionality to handle image clicks. This may be similar to issue #82. I'm using :perPageCustom="[[768, 3], [1024, 4]]"

**Comment by quinnlangille** [comment]
Hey @ianengelbrecht, it seems you're right in thinking that it's a similar issue to #82. Have you tried the most recent solution posted on that issue?
