### ISSUE TITLE
Documentation update:

### ISSUE THREAD

**Issue by mikestreety** [SSENSE/vue-carousel#92]
Hey! Thanks for an awesome plugin.

I might be worth noting in your documentation it can be used like the following - as in your demos you tend to build the items in the JS

It assumes `images` is an array of images.

```
<carousel>
    <slide v-for="(image, index) in images" :key="index">
        <img :alt="'Image ' + (index + 1)" :src="image" />
    </slide>
</carousel>
```

**Comment by quinnlangille** [comment]
Hey @mikestreety, thanks for the suggestion. I'm going to work on updating the documentation for the next patch.
