### ISSUE TITLE
Bug: video element is not supported as slides

### ISSUE THREAD

**Issue by Yishengtang** [SSENSE/vue-carousel#93]
I'm trying to put video elements as slides into the carousel, but the video can not play.

**Comment by quinnlangille** [comment]
Hey @Yishengtang, sorry for the late reply. There shouldn't be an issue with video on the input, have you since gotten it to work? If not, would you mind posting an image of how you're inserting the video?

**Comment by Yishengtang** [comment]
Thanks for the reply.

I have figured out what is happening in my code.

**Comment by quinnlangille** [comment]
👍 thanks!
